<style>
/*  3-landscape css start */
.landscape-3{
	background:#eef3fa;
	cursor:pointer;
	height:115px;
	overflow:hidden;	
}
.paddingadjust{
	padding:54px 38px 19px 50px !important;
}
#page_2 {
    color: #000000;
    font-family: "Open Sans","sans-serif";
    font-size: 22px;
    text-align: center;
    position: relative;
    top:3px;
}
/*3-landscape css end*/
</style>
<!--Frame Div Starts-->
<div class="col-xs-12 col-sm-8 col-md-8"> 
    <ul id="c-designer-header-tools">
        <li>Auto-fill<span class="icon-magic"></span></li>
        <li>Edit text<span class="icon-text-height"></span></li>
        <li>Clear collage<span class="icon-eraser"></span></li>
        <li class="pull-right"><a href="../index.php" style="color:#fff;">Change template<span class="icon-th"></span></a></li>
    </ul>
    <div id="c-designer">
        <div id="c-designer-layout-wrapper">
    <div id="c-layout" class="c-layout-43-3-h-txt-vacation1 col-xs-12 col-sm-12 col-lg-12 clgframboxvr2 paddingadjust">
      <div class="col-xs-12 col-sm-12  col-lg-12 ">
        <div class="row">
          <div  class=" col-xs-12 col-sm-4 col-lg-4 clgfrmimgltst5 clgletstbotom7  padding-left">
            <div id="c-slot-1" data-box-id="32" class="landscape-3 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
          </div>
          <div  class=" col-xs-12 col-sm-4 col-lg-4 clgfrmimgltst5 clgletstbotom7  padding-left">
            <div id="c-slot-2" data-box-id="33" class="landscape-3 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
          </div>
          <div  class=" col-xs-12 col-sm-4 col-lg-4 clgfrmimgltst5 clgletstbotom7  padding-left">
            <div id="c-slot-3" data-box-id="34" class="landscape-3 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
          </div>
          
        </div>
      </div>
      
      <div class="clearfix"></div>
      <span id="page_2">
                <div placeholder="Dein Text hier" id="c-text" class="seconds">Enter text here (Optional)</div>
            </span>
    </div>
    <div class="clearfix hidden-lg" style="height:20px;"></div>
  </div>
</div>         
</div>
<div id="get_slot_id"></div>
<!--Frame Div Ends-->