<style>
/*  4-mixed. css start */
.mixed-4frm{
	background:#eef3fa;
	cursor:pointer;
	height:490px;	
}
.mixed-4frmsm{
	background:#eef3fa;
	cursor:pointer;
	height:150px; 
	margin-bottom:20px;	
}
.paddingadjust{
	padding:50px 35px 16px 50px !important;
}
#page_2 {
    bottom: 75px;
    color: #000000;
    font-family: "Open Sans","sans-serif";
    font-size: 22px;
    min-height: 22px;
    position: relative;
    text-align: center;
    top: 0;
    width: 530px;
}
/*4-mixed. css end*/
</style>
<!--Frame Div Starts-->
<div class="col-xs-12 col-sm-8 col-md-8"> 
    <ul id="c-designer-header-tools">
        <li>Auto-fill<span class="icon-magic"></span></li>
        <li>Edit text<span class="icon-text-height"></span></li>
        <li>Clear collage<span class="icon-eraser"></span></li>
        <li class="pull-right"><a href="../index.php" style="color:#fff;">Change template<span class="icon-th"></span></a></li>
    </ul>
    <div id="c-designer">
        <div id="c-designer-layout-wrapper">
    <div id="c-layout" class="c-layout-43-3-h-txt-vacation1 col-xs-12 col-sm-12 col-lg-12 clgframboxvr2 paddingadjust">
      <div class="col-xs-12 col-sm-7  col-lg-7">
        <div class="row">
          <div  class="col-xs-12 col-sm-12 col-lg-12 clgfrmimgltst5 padding-left">
            <div id="c-slot-1" data-box-id="38" class="mixed-4frm c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
          </div>
        </div>
      </div>
       <div class="clear10 visible-xs"></div>
      <div class="col-xs-12 col-sm-5  col-lg-5 ">
        <div class="row">
          <div class="col-xs-12 col-sm-12 col-lg-12 clgfrmimgltst5 padding-left">
            <div id="c-slot-2" data-box-id="39" class="mixed-4frmsm c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
          </div>
          <div class="col-xs-12 col-sm-12 col-lg-12 clgfrmimgltst5 padding-left">
            <div id="c-slot-3" data-box-id="40" class="mixed-4frmsm c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
          </div>
          <div class="col-xs-12 col-sm-12 col-lg-12 clgfrmimgltst5 padding-left">
            <div id="c-slot-4" data-box-id="41" class="mixed-4frmsm c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
          </div>
        </div>
      </div>
      <div class="clearfix"></div>
	  <span id="page_2">
        <div placeholder="Dein Text hier" id="c-text" class="seconds">Enter text here (Optional)</div>
      </span>
    </div>
    <div class="clearfix hidden-lg" style="height:20px;"></div>
  </div>
</div>         
</div>
<div id="get_slot_id"></div>
<!--Frame Div Ends-->