<style>
    /*  4-portraitsn. css start */
    .portraits-4n{
        background: #eef3fa none repeat scroll 0 0;
        cursor: pointer;
        height: 365px;
        overflow: hidden;
        margin-bottom:12px;
       
        
    }
    .paddingadjust{
	padding: 50px 44px 15px 50px !important;
}
.clgfrmimgltst5 {
    padding-right: 12px;
}
    /*4-portraitsn. css end*/
</style>
<!--Frame Div Starts-->
<div class="col-xs-12 col-sm-8 col-md-8"> 
    <ul id="c-designer-header-tools">
        <li>Auto-fill<span class="icon-magic"></span></li>
        <li>Edit text<span class="icon-text-height"></span></li>
        <li>Clear collage<span class="icon-eraser"></span></li>
        <li class="pull-right"><a href="../index.php" style="color:#fff;">Change template<span class="icon-th"></span></a></li>
    </ul>
    <div id="c-designer" style="min-height:985px;">
        <div id="c-designer-layout-wrapper">
            <div id="c-layout" class="c-layout-43-3-h-txt-vacation1 col-xs-12 col-sm-12 col-lg-12 clgframboxvr2 paddingadjust" >
                <div class="col-xs-12 col-sm-12  col-lg-12 ">
                    <div class="row">
                        <div  class="col-xs-12 col-sm-6 col-lg-6 clgfrmimgltst5   padding-left">
                            <div id="c-slot-1" data-box-id="46" class="portraits-4n c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
                        </div>
                        <div  class="col-xs-12 col-sm-6 col-lg-6 clgfrmimgltst5   padding-left">
                            <div id="c-slot-2" data-box-id="47" class="portraits-4n  c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
                        </div>
                    </div>
                </div>
                <div class="clear10 visible-xs"></div>
                <div class="col-xs-12 col-sm-12  col-lg-12 ">
                    <div class="row">
                        <div  class="col-xs-12 col-sm-6 col-lg-6 clgfrmimgltst5   padding-left">
                            <div id="c-slot-3" data-box-id="48" class="portraits-4n  c-layout-slot rect-v pos-2 ui-droppable frm2ht"  style="overflow:hidden;"></div>
                        </div>
                        <div  class="col-xs-12 col-sm-6 col-lg-6 clgfrmimgltst5   padding-left">
                            <div id="c-slot-4" data-box-id="49" class="portraits-4n  c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
                        </div>
                    </div>
                </div>  
                <div class="clearfix"></div>
                <span id="page_2">
                    <div placeholder="Dein Text hier" id="c-text" class="seconds">Enter text here (Optional)</div>
                </span>
            </div>
            <div class="clearfix hidden-lg" style="height:20px;"></div>
        </div>
    </div>         
</div>
<div id="get_slot_id"></div>
<!--Frame Div Ends-->