<style>
/*5-portrait-line. css start*/
.portaitline5{
	width: 115px;	
}
.portrait-line-5{
	background:#eef3fa;
	cursor:pointer;
	height:135px;
	overflow:hidden;
	margin-bottom:20px;	
}
.paddingadjust{
	padding:38px 18px 0 38px !important;
}
#page_2 {
    top: -8px;
	}
/*5-portrait-line. css end*/
</style>
<!--Frame Div Starts-->
<div class="col-xs-12 col-sm-8 col-md-8"> 
    <ul id="c-designer-header-tools">
        <li>Auto-fill<span class="icon-magic"></span></li>
        <li>Edit text<span class="icon-text-height"></span></li>
        <li>Clear collage<span class="icon-eraser"></span></li>
        <li class="pull-right"><a href="../index.php" style="color:#fff;">Change template<span class="icon-th"></span></a></li>
    </ul>
    <div id="c-designer">
        <div id="c-designer-layout-wrapper">
    <div id="c-layout" class="c-layout-43-3-h-txt-vacation1 col-xs-12 col-sm-12 col-lg-12 clgframboxvr2 paddingadjust" >
      <div class="col-xs-12 col-sm-12  col-lg-12 ">
        <div class="row">
          <div  class=" col-xs-12 col-sm-3 col-lg-3 clgfrmimgltst5   padding-left portaitline5 ">
            <div id="c-slot-1" data-box-id="68" class="portrait-line-5 c-layout-slot rect-v pos-2 ui-droppable frm2ht" ></div>
          </div>
          <div  class=" col-xs-12 col-sm-3 col-lg-3 clgfrmimgltst5   padding-left portaitline5">
            <div id="c-slot-2" data-box-id="69" class="portrait-line-5 c-layout-slot rect-v pos-2 ui-droppable frm2ht"></div>
          </div>
          
          <div  class=" col-xs-12 col-sm-3 col-lg-3 clgfrmimgltst5   padding-left portaitline5">
            <div id="c-slot-3" data-box-id="70" class="portrait-line-5 c-layout-slot rect-v pos-2 ui-droppable frm2ht"></div>
          </div>
          
          <div  class="col-xs-12 col-sm-3 col-lg-3 clgfrmimgltst5   padding-left portaitline5">
            <div id="c-slot-4" data-box-id="71" class="portrait-line-5 c-layout-slot rect-v pos-2 ui-droppable frm2ht"></div>
          </div>
          
          <div  class="col-xs-12 col-sm-3 col-lg-3 clgfrmimgltst5   padding-left portaitline5">
            <div id="c-slot-5" data-box-id="72" class="portrait-line-5 c-layout-slot rect-v pos-2 ui-droppable frm2ht"></div>
          </div>
        </div>
      </div>
      <div class="clearfix"></div>
	  <span id="page_2">
		<div placeholder="Dein Text hier" id="c-text" class="seconds">Enter text here (Optional)</div>
	  </span>
    </div>
    <div class="clearfix hidden-lg" style="height:20px;"></div>
  </div>
</div>         
</div>
<div id="get_slot_id"></div>
<!--Frame Div Ends-->