<style>
/*square-4 css*/
.square-55{
	background:#eef3fa;
	cursor:pointer;
	height:315px;	
}
.square-67{
	background:#eef3fa;
	cursor:pointer;
	height: 95px;	
}
.square-77{
	background:#eef3fa;
	cursor:pointer;
	height: 150px;	
}
.padding0{
	padding:0;
}
.paddingadjust{
    padding: 51px 10px 30px 40px !important;
}
.clgfrmimgltst5 {
    padding-right: 15px !important;
}
.clgletstbotom7 {
    margin-bottom: 15px !important;
}
/*square-4css end*/
</style>
<!--Frame Div Starts-->
<div class="col-xs-12 col-sm-8 col-md-8"> 
    <ul id="c-designer-header-tools">
        <li>Auto-fill<span class="icon-magic"></span></li>
        <li>Edit text<span class="icon-text-height"></span></li>
        <li>Clear collage<span class="icon-eraser"></span></li>
        <li class="pull-right"><a href="../index.php" style="color:#fff;">Change template<span class="icon-th"></span></a></li>
    </ul>
    <div id="c-designer">
        <div id="c-designer-layout-wrapper">
			<div id="c-layout" class="c-layout-43-3-h-txt-vacation1 col-xs-12 col-sm-12 col-lg-12 clgframboxvr2 paddingadjust" >
			  <div class="col-xs-12 col-sm-12  col-lg-12 ">
				<div class="row">
				  <div  class=" col-xs-12 col-sm-5 col-lg-5 clgfrmimgltst5 padding-left ">
					<div  class=" col-xs-12 col-sm-12 col-lg-12 padding0">
						<div id="c-slot-1" data-box-id="95" class="square-55 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
					</div>
				  </div>
				  <div class="col-xs-12 col-sm-3 col-lg-3 clgfrmimgltst5 padding-left">
						<div  class=" col-xs-12 col-sm-12 col-lg-12 padding0 clgletstbotom7">
							<div id="c-slot-2" data-box-id="96" class="square-67 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
						</div>
						<div  class=" col-xs-12 col-sm-12 col-lg-12 padding0 clgletstbotom7">
							<div id="c-slot-3" data-box-id="97" class="square-67 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
						</div>
						<div  class=" col-xs-12 col-sm-12 col-lg-12 padding0 clgletstbotom7">
							<div id="c-slot-4" data-box-id="98" class="square-67 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
						</div>
				  </div>
				  <div class="col-xs-12 col-sm-4 col-lg-4 clgfrmimgltst5 padding-left">
					<div  class=" col-xs-12 col-sm-12 col-lg-12 padding0 clgletstbotom7">
						<div id="c-slot-5" data-box-id="99" class="square-77 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
					</div>
					<div  class=" col-xs-12 col-sm-12 col-lg-12 padding0 clgletstbotom7">
						<div id="c-slot-6" data-box-id="100" class="square-77 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
					</div>
				  </div>
				</div>
			  </div>
			  <div class="clearfix"></div>
			  <span id="page_2">
				<div placeholder="Dein Text hier" id="c-text" class="seconds">Enter text here (Optional)</div>
			  </span>
			</div>
			<div class="clearfix hidden-lg" style="height:20px;"></div>
		</div>
	</div>         
</div>
<div id="get_slot_id"></div>
<!--Frame Div Ends-->