<style>
/*square-4 css*/
.square-23{
	background:#eef3fa;
	cursor:pointer;
	height:350px;	
}
.square-22{
	background:#eef3fa;
	cursor:pointer;
	height: 164px;	
}
.paddingadjust{
    padding: 51px 35px 30px 55px !important;
}
/*square-4css end*/
</style>
<!--Frame Div Starts-->
<div class="col-xs-12 col-sm-8 col-md-8"> 
    <ul id="c-designer-header-tools">
        <li>Auto-fill<span class="icon-magic"></span></li>
        <li>Edit text<span class="icon-text-height"></span></li>
        <li>Clear collage<span class="icon-eraser"></span></li>
        <li class="pull-right"><a href="../index.php" style="color:#fff;">Change template<span class="icon-th"></span></a></li>
    </ul>
    <div id="c-designer">
        <div id="c-designer-layout-wrapper">
			<div id="c-layout" class="c-layout-43-3-h-txt-vacation1 col-xs-12 col-sm-12 col-lg-12 clgframboxvr2 paddingadjust" >
			  <div class="col-xs-12 col-sm-12  col-lg-12 ">
				<div class="row">
				  <div  class=" col-xs-12 col-sm-8 col-lg-8 clgfrmimgltst5 clgletstbotom7 padding-left ">
					<div id="c-slot-1" data-box-id="119" class="square-23 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
				  </div>
				  <div class="col-xs-12 col-sm-4 col-lg-4 clgfrmimgltst5 clgletstbotom7 padding-left">
					<div id="c-slot-2" data-box-id="120" class="square-22 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
				  </div>
				  <div class="col-xs-12 col-sm-4 col-lg-4 clgfrmimgltst5 padding-left">
					<div id="c-slot-3" data-box-id="121" class="square-22 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
				  </div>
				</div>
			  </div>
			  <div class="col-xs-12 col-sm-12  col-lg-12 ">
				<div class="row">
				  <div class="col-xs-12 col-sm-4 col-lg-4 clgfrmimgltst5 padding-left">
					<div id="c-slot-4" data-box-id="122" class="square-22 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
				  </div>
				  <div class="col-xs-12 col-sm-4 col-lg-4 clgfrmimgltst5 padding-left">
					<div id="c-slot-5" data-box-id="123" class="square-22 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
				  </div>
				  <div class="col-xs-12 col-sm-4 col-lg-4 clgfrmimgltst5 padding-left">
					<div id="c-slot-6" data-box-id="124" class="square-22 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
				  </div>
				</div>
			  </div>
			  <div class="clearfix"></div>
			  <span id="page_2">
				<div placeholder="Dein Text hier" id="c-text" class="seconds">Enter text here (Optional)</div>
			  </span>
			</div>
			<div class="clearfix hidden-lg" style="height:20px;"></div>
		</div>
	</div>         
</div>
<div id="get_slot_id"></div>
<!--Frame Div Ends-->