
<style>
    
    .paddingadjust{
	padding: 50px 68px 26px 50px !important;
}</style>
<!--Frame Div Starts-->
<div class="col-xs-12 col-sm-8 col-md-8  "> 
    <ul id="c-designer-header-tools">
        <li>Auto-fill<span class="icon-magic"></span></li>
<!--        class="icon-text-height"-->
<li class="c-text-3">Edit text<span id="text_3"></span></li>
        <li>Clear collage<span class="icon-eraser"></span></li>
        <li class="pull-right"><a href="../index.php" style="color:#fff;">Change template<span class="icon-th"></span></a></li>
    </ul>
    <div class="cf livemode" id="c-designer">
        <div id="c-designer-layout-wrapper">
            <div id="c-layout" class="col-xs-12 col-sm-12 clgframboxbaby paddingadjust">
                <div class="row">
                    <div  id="c-slot-1" data-box-id="7" class="col-xs-12 col-sm-4 col-lg-4 padingright0">
                        <div id="c-slot-1" class="c-layout-slot rect-v pos-1 ui-droppable clgimgsltest2" style="overflow:hidden;">
                        </div>
                    </div>
                    <div id="c-slot-2" data-box-id="8" class=" col-xs-12 col-sm-4 col-lg-4  padingright0">
                        <div id="c-slot-2" class="c-layout-slot rect-v pos-2 ui-droppable clgimgsltest2" style="overflow:hidden;">
                        </div>
                    </div>
                    <div id="c-slot-3" data-box-id="9" class="col-xs-12 col-sm-4 col-lg-4  padingright0">
                        <div id="c-slot-3" class=" c-layout-slot rect-v pos-3 ui-droppable clgimgsltest2" style="overflow:hidden;">
                        </div>
						<div id="tex_p" style="margin-left:-134px;position: releative">
							<div placeholder="Dein Text hier" class="second"  id="text_3">Enter text here (Optional)</div>    
						</div>
                	</div>
					<div class="clearfix"></div>		
				</div>   
            </div>      
        </div>
    </div>
</div>
<div id="c-designer-modal">
	<div id="c-designer-modal-content">
		<h4>Crop image<span class="icon-move"></span></h4>
		<div id="c-designer-modal-crop" style="width: 280px; height: 430px;">
			<img alt="modal image" id="c-designer-modal-img" width="280" height="430" src="" style="width: 280px; height: 430px; display: inline; visibility: visible;">
		</div>
		<span id="c-designer-modal-crop-confirm" class="btn btn-green"><span>Apply</span> <i class="glyphicon glyphicon-ok"></i></span> 
	</div>
</div>
<div id="get_slot_id"></div>
<!--Frame Div Ends-->
