
<style>
    .square_fas_2{
        background:#eef3fa;
        cursor:pointer;
        height:130px;	
    }
    .square_fa_3{
        background:#eef3fa;
        cursor:pointer;
        height: 130px;
    }
    .square_fasi_1{
        background:#eef3fa;
        cursor:pointer;
        height: 206px;

    }
    .square_fasi_5{
        background:#eef3fa;
        cursor:pointer;
        height: 206px;
    }
    .padding0{
        padding:0;
    }
    .pad-rit {
        padding-right:4px;
    }
    .pad-lft {
        padding-left:4px;
    }
    .clgletstbotom7 {
        margin-bottom: 10px;
    }
    .paddingadjust{
        padding: 51px 0px 30px 55px !important;
    }
    .clgfrmimgltst5 {
        padding-right: 9px;
    }
</style>
<!--Frame Div Starts-->
<div class="col-xs-12 col-sm-8 col-md-8"> 
    <ul id="c-designer-header-tools">
        <li>Auto-fill<span class="icon-magic"></span></li>
        <li>Edit text<span class="icon-text-height"></span></li>
        <li>Clear collage<span class="icon-eraser"></span></li>
        <li class="pull-right"><a href="../index.php" style="color:#fff;">Change template<span class="icon-th"></span></a></li>
    </ul>
    <div id="c-designer">
        <div id="c-designer-layout-wrapper">
            <div id="c-layout" class="c-layout-43-3-h-txt-vacation1 col-xs-12 col-sm-12 col-lg-12 clgframboxvr2 paddingadjust" >
                <div class="col-xs-12 col-sm-12  col-lg-12 ">
                    <div class="row">
                        <div class="col-xs-12 col-sm-3 col-lg-3 clgfrmimgltst5 clgletstbotom7 padding-left">
                            <div class="col-xs-12 col-sm-12 col-lg-12 padding0 clgletstbotom7">				
                                <div id="c-slot-1" data-box-id="132" class="square_fasi_1 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
                            </div>
                            <div class="col-xs-12 col-sm-12 col-lg-12 padding0">				
                                <div id="c-slot-2" data-box-id="133" class="square_fas_2 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-5 col-lg-5 clgfrmimgltst5 padding-left">
                            <div class="col-xs-12 col-sm-12 col-lg-12 clgletstbotom7  padding0">
                                <div id="c-slot-3" data-box-id="134" class="square_fasi_1 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
                            </div>
                            <div class="col-xs-12 col-sm-6 col-lg-6  clgletstbotom7 padding-left padding0 pad-rit" >
                                <div id="c-slot-4" data-box-id="135" class="square_fa_3 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
                            </div>
                            <div class="col-xs-12 col-sm-6 col-lg-6 clgletstbotom7 padding-left padding0 pad-lft">
                                <div id="c-slot-5" data-box-id="136" class="square_fa_3 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-3 col-lg-3 clgfrmimgltst5 clgletstbotom7 padding-left">

                            <div class="col-xs-12 col-sm-12 col-lg-12 padding0 clgletstbotom7">				
                                <div id="c-slot-6" data-box-id="137" class="square_fas_2 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
                            </div>
                            <div class="col-xs-12 col-sm-12 col-lg-12 padding0 ">				
                                <div id="c-slot-7" data-box-id="138" class="square_fasi_1 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="clearfix"></div>
                <span id="page_2">
                    <div placeholder="Dein Text hier" id="c-text" class="seconds">Enter text here (Optional)</div>
                </span>
            </div>
            <div class="clearfix hidden-lg" style="height:20px;"></div>
        </div>
    </div>         
</div>
<div id="get_slot_id"></div>
<!--Frame Div Ends-->