<style>
    /*square-4 css*/
    .square-upright{
        background:#eef3fa;
        cursor:pointer;
        height:270px;	
    }
    .square-upright-99{
        background:#eef3fa;
        cursor:pointer;
        height: 200px;	
    }
    .clgfrmimgltst5 {
        padding-right: 12px;
    }
    #c-designer {
        background: rgb(226, 226, 226) none repeat scroll 0 0;
        margin-bottom: 60px;
        min-height: 890px;
        padding: 55px 80px 80px;
        width: 100%;
    }
    /*square-4css end*/
</style>
<!--Frame Div Starts-->
<div class="col-xs-12 col-sm-8 col-md-8"> 
    <ul id="c-designer-header-tools">
        <li>Auto-fill<span class="icon-magic"></span></li>
        <li>Edit text<span class="icon-text-height"></span></li>
        <li>Clear collage<span class="icon-eraser"></span></li>
        <li class="pull-right"><a href="../index.php" style="color:#fff;">Change template<span class="icon-th"></span></a></li>
    </ul>
    <div id="c-designer">
        <div id="c-designer-layout-wrapper">
            <div id="c-layout" class="c-layout-43-3-h-txt-vacation1 col-xs-12 col-sm-12 col-lg-12 clgframboxvr2">
                <div class="col-xs-12 col-sm-12  col-lg-12 ">
                    <div class="row">
                        <div  class=" col-xs-12 col-sm-4 col-lg-4 clgfrmimgltst5 clgletstbotom7 padding-left ">
                            <div id="c-slot-1" data-box-id="139" class="square-upright-99 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
                        </div>
                        <div  class=" col-xs-12 col-sm-4 col-lg-4 clgfrmimgltst5 clgletstbotom7 padding-left ">
                            <div id="c-slot-2" data-box-id="140" class="square-upright-99 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
                        </div>
                        <div  class=" col-xs-12 col-sm-4 col-lg-4 clgfrmimgltst5 clgletstbotom7 padding-left ">
                            <div id="c-slot-3" data-box-id="141" class="square-upright-99 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
                        </div>
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12  col-lg-12 ">
                    <div class="row">
                        <div  class=" col-xs-12 col-sm-12 col-lg-12 clgfrmimgltst5 clgletstbotom7 padding-left ">
                            <div id="c-slot-4" data-box-id="142" class="square-upright c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
                        </div>
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12  col-lg-12 ">
                    <div class="row">
                        <div  class=" col-xs-12 col-sm-4 col-lg-4 clgfrmimgltst5 clgletstbotom7 padding-left ">
                            <div id="c-slot-5" data-box-id="143" class="square-upright-99 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
                        </div>
                        <div  class=" col-xs-12 col-sm-4 col-lg-4 clgfrmimgltst5 clgletstbotom7 padding-left ">
                            <div id="c-slot-6" data-box-id="144" class="square-upright-99 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
                        </div>
                        <div  class=" col-xs-12 col-sm-4 col-lg-4 clgfrmimgltst5 clgletstbotom7 padding-left ">
                            <div id="c-slot-7" data-box-id="145" class="square-upright-99 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
                        </div>
                    </div>
                </div>
                <div class="clearfix"></div>
                <span id="page_2">
                    <div placeholder="Dein Text hier" id="c-text" class="seconds">Enter text here (Optional)</div>
                </span>
            </div>
            <div class="clearfix hidden-lg" style="height:20px;"></div>
        </div>
    </div>         
</div>
<div id="get_slot_id"></div>
<!--Frame Div Ends-->