<style>
    /*square-4 css*/
    .square-7-apertures{
        background:#eef3fa;
        cursor:pointer;
        height:321px;	
    }
    .square-apertures-7{
        background:#eef3fa;
        cursor:pointer;
        height: 100px;	
        width: 150px;	
    }
    .clgfrmimgltst5 {
        padding-right: 10px;
    }
    .clgletstbotom7 {
        margin-bottom: 10px;
    }
	.paddingadjust{
    padding:51px 2px 30px 45px !important;
}
    .padding0{
        padding:0;
    }
    /*square-4css end*/
</style>
<!--Frame Div Starts-->
<div class="col-xs-12 col-sm-8 col-md-8"> 
    <ul id="c-designer-header-tools">
        <li>Auto-fill<span class="icon-magic"></span></li>
        <li>Edit text<span class="icon-text-height"></span></li>
        <li>Clear collage<span class="icon-eraser"></span></li>
        <li class="pull-right"><a href="../index.php" style="color:#fff;">Change template<span class="icon-th"></span></a></li>
    </ul>
    <div id="c-designer">
        <div id="c-designer-layout-wrapper">
            <div id="c-layout" class="c-layout-43-3-h-txt-vacation1 col-xs-12 col-sm-12 col-lg-12 clgframboxvr2 paddingadjust" >
                <div class="col-xs-12 col-sm-12  col-lg-12 ">
                    <div class="row">

                        <div class="col-xs-12 col-sm-3 col-lg-3 clgfrmimgltst5 clgletstbotom7 padding-left">
                            <div  class=" col-xs-12 col-sm-12 col-lg-12 padding0 clgletstbotom7">
                                <div id="c-slot-1" data-box-id="146" class="square-apertures-7 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
                            </div>
                            <div  class=" col-xs-12 col-sm-12 col-lg-12 padding0 clgletstbotom7">
                                <div id="c-slot-2" data-box-id="147" class="square-apertures-7 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
                            </div>
                            <div  class=" col-xs-12 col-sm-12 col-lg-12 padding0 clgletstbotom7">
                                <div id="c-slot-3" data-box-id="148" class="square-apertures-7 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
                            </div>
                        </div>
                        <div  class=" col-xs-12 col-sm-5 col-lg-5 clgfrmimgltst5 clgletstbotom7" style="padding-left: 14px;">
                            <div  class=" col-xs-12 col-sm-12 col-lg-12 padding0">
                                <div id="c-slot-4" data-box-id="149" class="square-7-apertures c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-3 col-lg-3 clgfrmimgltst5 clgletstbotom7 padding-left">
                            <div  class=" col-xs-12 col-sm-12 col-lg-12 padding0 clgletstbotom7">
                                <div id="c-slot-5" data-box-id="150" class="square-apertures-7 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
                            </div>
                            <div  class=" col-xs-12 col-sm-12 col-lg-12 padding0 clgletstbotom7">
                                <div id="c-slot-6" data-box-id="151" class="square-apertures-7 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
                            </div>
                            <div  class=" col-xs-12 col-sm-12 col-lg-12 padding0 clgletstbotom7">
                                <div id="c-slot-7" data-box-id="152" class="square-apertures-7 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="clearfix"></div>
                <span id="page_2">
                    <div placeholder="Dein Text hier" id="c-text" class="seconds">Enter text here (Optional)</div>
                </span>
            </div>
            <div class="clearfix hidden-lg" style="height:20px;"></div>
        </div>
    </div>         
</div>
<div id="get_slot_id"></div>
<!--Frame Div Ends-->