<style>
    /*square-4 css*/
    .square-mixed-aperedrd{
        background:#eef3fa;
        cursor:pointer;
        height:140px;	
		width:95px;	
    
    }
    .square-mixed-aper{
        background:#eef3fa;
        cursor:pointer;
        height:290px;	
    }
    .square-mixed{
        background:#eef3fa;
        cursor:pointer;
        height:140px;	
    }
    .clgfrmimgltst5 {
        padding-right: 10px;
    }
    .clgletstbotom7 {
        margin-bottom: 10px;
    }
    .padding0 {
        padding:0;
    }
    .paddingadjust{
        padding: 51px 55px 30px 45px !important;
    }
    /*square-4css end*/
</style>
<!--Frame Div Starts-->

<div class="col-xs-12 col-sm-8 col-md-8"> 
    <ul id="c-designer-header-tools">
        <li>Auto-fill<span class="icon-magic"></span></li>
        <li>Edit text<span class="icon-text-height"></span></li>
        <li>Clear collage<span class="icon-eraser"></span></li>
        <li class="pull-right"><a href="../index.php" style="color:#fff;">Change template<span class="icon-th"></span></a></li>
    </ul>
    <div id="c-designer">
        <div id="c-designer-layout-wrapper">
            <div id="c-layout" class="c-layout-43-3-h-txt-vacation1 col-xs-12 col-sm-12 col-lg-12 clgframboxvr2 paddingadjust" >
                <div class="col-xs-12 col-sm-12  col-lg-12 ">
                    <div class="row">
                         <div  class=" col-xs-12 col-sm-5 col-lg-5 clgfrmimgltst5 clgletstbotom7 padding-left " style="padding-left: 20px;">
                            <div  class=" col-xs-12 col-sm-12 col-lg-12 clgfrmimgltst5  clgletstbotom7    padding0">
                                <div id="c-slot-1" data-box-id="153" class="square-mixed-aper c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
                            </div>
							<div  class=" col-xs-12 col-sm-12 col-lg-12 padding0">
                                <div id="c-slot-2" data-box-id="154" class="square-mixed c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
                            </div>
                        </div>
                        <div  class=" col-xs-12 col-sm-2 col-lg-2 clgfrmimgltst5 clgletstbotom7 padding-left ">
                            <div  class=" col-xs-12 col-sm-12 col-lg-12 padding0 clgfrmimgltst5 clgletstbotom7">
                                <div id="c-slot-3" data-box-id="155" class="square-mixed-aperedrd c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
                            </div>
                            <div  class=" col-xs-12 col-sm-12 col-lg-12 padding0 clgfrmimgltst5 clgletstbotom7">
                                <div id="c-slot-4" data-box-id="156" class="square-mixed-aperedrd c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
                            </div>
                            <div  class=" col-xs-12 col-sm-12 col-lg-12 padding0 clgfrmimgltst5 clgletstbotom7">
                                <div id="c-slot-5" data-box-id="157" class="square-mixed-aperedrd c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
                            </div>
                        </div>
                        <div  class=" col-xs-12 col-sm-5 col-lg-5 clgfrmimgltst5 clgletstbotom7 padding-left " style="padding-left: 17px;">
                            <div  class=" col-xs-12 col-sm-12 col-lg-12 padding0 clgletstbotom7 ">
                                <div id="c-slot-6" data-box-id="158" class="square-mixed c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
                            </div>
                            <div  class=" col-xs-12 col-sm-12 col-lg-12 clgfrmimgltst5   padding0">
                                <div id="c-slot-7" data-box-id="159" class="square-mixed-aper c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="clearfix"></div>
                <span id="page_2">
                    <div placeholder="Dein Text hier" id="c-text" class="seconds">Enter text here (Optional)</div>
                </span>
            </div>
            <div class="clearfix hidden-lg" style="height:20px;"></div>
        </div>
    </div>         
</div>
<div id="get_slot_id"></div>
<!--Frame Div Ends-->