<style>
    /*square-4 css*/
    .square-8-apertures-1{
        background:#eef3fa;
        cursor:pointer;
        height:200px;	
    }
    .square-8-apertures-2{
        background:#eef3fa;
        cursor:pointer;
        height: 122px;	
    }
    .padding0 {
        padding:0;
    }
    .clgfrmimgltst5 {
        padding-right: 10px;
    }
    .clgletstbotom7 {
        margin-bottom: 10px;
    }

    #c-designer-layout-wrapper {
        float: left;
        height: 578px;
        padding: 6px 70px 70px;
        position: relative;
        width: 100%;
    }
    /*square-4css end*/
</style>
<!--Frame Div Starts-->
<div class="col-xs-12 col-sm-8 col-md-8"> 
    <ul id="c-designer-header-tools">
        <li>Auto-fill<span class="icon-magic"></span></li>
        <li>Edit text<span class="icon-text-height"></span></li>
        <li>Clear collage<span class="icon-eraser"></span></li>
        <li class="pull-right"><a href="../index.php" style="color:#fff;">Change template<span class="icon-th"></span></a></li>
    </ul>
    <div id="c-designer">
        <div id="c-designer-layout-wrapper">
            <div id="c-layout" class="c-layout-43-3-h-txt-vacation1 col-xs-12 col-sm-12 col-lg-12 clgframboxvr2" >
                <div class="col-xs-12 col-sm-12  col-lg-12 ">
                    <div class="row">
                        <div  class=" col-xs-12 col-sm-6 col-lg-6 clgfrmimgltst5 clgletstbotom7 padding-left ">
                            <div id="c-slot-1" data-box-id="167" class="square-8-apertures-1 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
                        </div>
                        <div  class=" col-xs-12 col-sm-6 col-lg-6 clgfrmimgltst5 clgletstbotom7 padding-left ">
                            <div id="c-slot-2" data-box-id="168" class="square-8-apertures-1 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
                        </div>

                    </div>
                </div>
                <div class="col-xs-12 col-sm-12  col-lg-12 ">
                    <div class="row">
                        <div  class=" col-xs-12 col-sm-4 col-lg-4 clgfrmimgltst5 clgletstbotom7 padding-left ">
                            <div id="c-slot-3" data-box-id="169" class="square-8-apertures-2 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
                        </div>
                        <div  class=" col-xs-12 col-sm-4 col-lg-4 clgfrmimgltst5 clgletstbotom7 padding-left ">
                            <div id="c-slot-4" data-box-id="170" class="square-8-apertures-2 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
                        </div>
                        <div  class=" col-xs-12 col-sm-4 col-lg-4 clgfrmimgltst5 clgletstbotom7 padding-left ">
                            <div id="c-slot-5" data-box-id="171" class="square-8-apertures-2 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
                        </div>
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12  col-lg-12 ">
                    <div class="row">
                        <div  class=" col-xs-12 col-sm-6 col-lg-6 clgfrmimgltst5 clgletstbotom7 padding-left ">
                            <div id="c-slot-6" data-box-id="172" class="square-8-apertures-1 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
                        </div>
                        <div  class=" col-xs-12 col-sm-6 col-lg-6 clgfrmimgltst5 clgletstbotom7 padding-left ">
                            <div id="c-slot-7" data-box-id="173" class="square-8-apertures-1 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
                        </div>
                    </div>
                </div>
                <div class="clearfix"></div>
                <span id="page_2">
                    <div placeholder="Dein Text hier" id="c-text" class="seconds">Enter text here (Optional)</div>
                </span>
            </div>
            <div class="clearfix hidden-lg" style="height:20px;"></div>
        </div>
    </div>         
</div>
<div id="get_slot_id"></div>
<!--Frame Div Ends-->