<style>
    /*square-4 css*/
    .square-d-apertures-9{
        background:#eef3fa;
        cursor:pointer;
        height:165px;	
    }
    .square-c-apertures-4{
        background:#eef3fa;
        cursor:pointer;
        height: 107px;
        width: 107px;
       
	}
    .padding0 {
        padding:0;
    }
    .clgfrmimgltst5 {
    padding-right: 4px;
}
    #c-designer-layout-wrapper {
    float: left;
    height: 578px;
    padding: 20px;
    position: relative;
    width: 100%;
    }
    .clgletstbotom7 {
        margin-bottom: 10px;
    }
    .paddingadjust{
        padding:57px 16px 27px 61px  !important;
    }
    /*square-4css end*/
</style>
<!--Frame Div Starts-->
<div class="col-xs-12 col-sm-8 col-md-8"> 
    <ul id="c-designer-header-tools">
        <li>Auto-fill<span class="icon-magic"></span></li>
        <li>Edit text<span class="icon-text-height"></span></li>
        <li>Clear collage<span class="icon-eraser"></span></li>
        <li class="pull-right"><a href="../index.php" style="color:#fff;">Change template<span class="icon-th"></span></a></li>
    </ul>
    <div id="c-designer">
        <div id="c-designer-layout-wrapper">
            <div id="c-layout" class="c-layout-43-3-h-txt-vacation1 col-xs-12 col-sm-12 col-lg-12 clgframboxvr2 paddingadjust">
                <div class="col-xs-12 col-sm-12  col-lg-12 ">
                    <div class="row">
                        <div class="col-xs-12 col-sm-4 col-lg-4 padding0 ">
                            <div  class="  col-xs-12 col-sm-12 col-lg-12 clgletstbotom7 padding-left padding0">
                                <div id="c-slot-1" data-box-id="174" class="square-d-apertures-9 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
                            </div>
                            <div  class="  col-xs-12 col-sm-12 col-lg-12 clgletstbotom7 padding-left padding0">
                                <div id="c-slot-2" data-box-id="175" class="square-d-apertures-9 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-3 col-lg-3 padding0 "style=" padding-left: 10px;" >
                            <div  class="  col-xs-12 col-sm-12 col-lg-12  clgletstbotom7 padding-left padding0">
                                <div id="c-slot-3" data-box-id="176" class="square-c-apertures-4 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
                            </div>
                            <div  class="  col-xs-12 col-sm-12 col-lg-12 clgletstbotom7 padding-left padding0">
                                <div id="c-slot-4" data-box-id="177" class="square-c-apertures-4 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
                            </div>
                            <div  class="  col-xs-12 col-sm-12 col-lg-12 clgletstbotom7 padding-left padding0">
                                <div id="c-slot-5" data-box-id="178" class="square-c-apertures-4 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-4 col-lg-4 padding0">
                            <div  class=" col-xs-12 col-sm-12 col-lg-12 clgletstbotom7 padding-left padding0">
                                <div id="c-slot-6" data-box-id="179" class="square-d-apertures-9 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
                            </div>
                            <div  class=" col-xs-12 col-sm-12 col-lg-12 clgletstbotom7 padding-left padding0">
                                <div id="c-slot-7" data-box-id="180" class="square-d-apertures-9 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="clearfix"></div>
                <span id="page_2">
                    <div placeholder="Dein Text hier" id="c-text" class="seconds">Enter text here (Optional)</div>
                </span>
            </div>
            <div class="clearfix hidden-lg" style="height:20px;"></div>
        </div>
    </div>         
</div>
<div id="get_slot_id"></div>
<!--Frame Div Ends-->