<style>
    /*9 aperture-1-upright css start*/
    .apertures-9upright1 {
        background: #eef3fa;
        height:210px;
        overflow: hidden;
        margin-bottom: 10px;
    }
    .apertures-9upright1lg {
        background: #eef3fa;
        height: 310px;
        overflow: hidden;
        margin-bottom: 10px;
    }
    .apertures-9upright1md {
        background: #eef3fa;
        height: 150px;
        overflow: hidden;
        margin-bottom: 10px;
    }
    .apertures-9upright1sm {
        background: #eef3fa;
        height: 150px;
        overflow: hidden;
        margin-bottom: 10px;
    }
    .clgfrmimgltst5 {
        padding-right: 10px;
    }
    .paddingadjust{
        padding: 40px 35px 30px 40px !important;
    }
    #c-designer {
        background: rgb(226, 226, 226) none repeat scroll 0 0;
        margin-bottom: 60px;
        min-height: 1041px;
        padding: 1px;
        width: 100%;
    }
</style>
<!--Frame Div Starts-->

<div class="col-xs-12 col-sm-8 col-md-8">
    <ul id="c-designer-header-tools">
        <li>Auto-fill<span class="icon-magic"></span></li>
        <li>Edit text<span class="icon-text-height"></span></li>
        <li>Clear collage<span class="icon-eraser"></span></li>
        <li class="pull-right"><a href="../index.php" style="color:#fff;">Change template<span class="icon-th"></span></a></li>
    </ul>
    <div id="c-designer">
        <div id="c-designer-layout-wrapper">
            <div id="c-layout" class="c-layout-43-3-h-txt-vacation1 col-xs-12 col-sm-12 col-lg-12 clgframboxvr2 paddingadjust" >
                <div class="col-xs-12 col-sm-12  col-lg-12 ">
                    <div class="row">
                        <div  class="col-xs-12 col-sm-7 col-lg-7 clgfrmimgltst5   padding-left">
                            <div id="c-slot-1" data-box-id="206" class="apertures-9upright1 c-layout-slot rect-v pos-2 ui-droppable frm2ht" ></div>
                        </div>
                        <div  class="col-xs-12 col-sm-5 col-lg-5 clgfrmimgltst5   padding-left">
                            <div id="c-slot-2" data-box-id="207" class="apertures-9upright1 c-layout-slot rect-v pos-2 ui-droppable frm2ht"></div>
                        </div>
                    </div>
                </div>
                <div class="clearfix visible-xs" style="height:20px;"></div>
                <div class="col-xs-12 col-sm-12  col-lg-12 ">
                    <div class="row">
                        <div  class="col-xs-12 col-sm-2 col-lg-2 clgfrmimgltst5   padding-left">
                            <div class="col-xs-12 col-sm-12  col-lg-12 padding">
                                <div id="c-slot-3" data-box-id="208" class="apertures-9upright1sm c-layout-slot rect-v pos-2 ui-droppable frm2ht" ></div>
                            </div>
                            <div class="col-xs-12 col-sm-12  col-lg-12 padding">
                                <div id="c-slot-4" data-box-id="209" class="apertures-9upright1sm c-layout-slot rect-v pos-2 ui-droppable frm2ht" ></div>
                            </div>
                        </div>
                        <div  class="col-xs-12 col-sm-5 col-lg-5 clgfrmimgltst5   padding-left">
                            <div id="c-slot-5" data-box-id="210" class="apertures-9upright1lg c-layout-slot rect-v pos-2 ui-droppable frm2ht" ></div>
                        </div> 
                        <div  class="col-xs-12 col-sm-5 col-lg-5 clgfrmimgltst5   padding-left">
                            <div class="col-xs-12 col-sm-12  col-lg-12 padding">
                                <div id="c-slot-6" data-box-id="211" class="apertures-9upright1md c-layout-slot rect-v pos-2 ui-droppable frm2ht" ></div>
                            </div>
                            <div class="col-xs-12 col-sm-12  col-lg-12 padding">
                                <div id="c-slot-7" data-box-id="212" class="apertures-9upright1md c-layout-slot rect-v pos-2 ui-droppable frm2ht" ></div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="clearfix visible-xs" style="height:20px;"></div>
                <div class="col-xs-12 col-sm-12  col-lg-12 ">
                    <div class="row">
                        <div  class="col-xs-12 col-sm-5 col-lg-5 clgfrmimgltst5   padding-left">
                            <div id="c-slot-8" data-box-id="213" class="apertures-9upright1 c-layout-slot rect-v pos-2 ui-droppable frm2ht"></div>
                        </div>
                        <div  class="col-xs-12 col-sm-7 col-lg-7 clgfrmimgltst5   padding-left">
                            <div id="c-slot-9" data-box-id="214" class="apertures-9upright1 c-layout-slot rect-v pos-2 ui-droppable frm2ht" ></div>
                        </div>
                    </div>
                </div>
                <div class="clearfix"></div>
                <span id="page_2">
                    <div placeholder="Dein Text hier" id="c-text" class="seconds">Enter text here (Optional)</div>
                </span> </div>
            <div class="clearfix hidden-lg" style="height:20px;"></div>
        </div>
    </div>
</div>
<div id="get_slot_id"></div>
<!--Frame Div Ends-->