<style>
    /*square-4 css*/
    .square_fas_2{
        background:#eef3fa;
        cursor:pointer;
        height:156px;	
    }
    .ap-1{
        background:#eef3fa;
        cursor:pointer;
        height: 58px;	
    }
    .ap-2{
        background:#eef3fa;
        cursor:pointer;
        height: 134px;	
    }
    .sq-3{
        background:#eef3fa;
        cursor:pointer;
        height: 134px;	
    }
    .ap-4{
        background:#eef3fa;
        cursor:pointer;
        height: 132px;	
    }
    .squ-5{
        background:#eef3fa;
        cursor:pointer;
        height: 200px;	
    }
    .padding0{
        padding:0;
    }
    .pad-rit {
        padding-right:3px;
    }
    .pad-lft {
        padding-left:3px;
    }
    .clgletstbotom7 {
        margin-bottom: 10px;
    }
    .paddingadjust{
        padding: 51px 31px 30px 28px !important;
    }
    .clgfrmimgltst5 {
        padding-right: 9px;
    }
    /*square-4css end*/
</style>
<!--Frame Div Starts-->
<div class="col-xs-12 col-sm-8 col-md-8"> 
    <ul id="c-designer-header-tools">
        <li>Auto-fill<span class="icon-magic"></span></li>
        <li>Edit text<span class="icon-text-height"></span></li>
        <li>Clear collage<span class="icon-eraser"></span></li>
        <li class="pull-right"><a href="../index.php" style="color:#fff;">Change template<span class="icon-th"></span></a></li>
    </ul>
    <div id="c-designer">
        <div id="c-designer-layout-wrapper">
            <div id="c-layout" class="c-layout-43-3-h-txt-vacation1 col-xs-12 col-sm-12 col-lg-12 clgframboxvr2 paddingadjust" >
                <div class="col-xs-12 col-sm-12  col-lg-12 ">
                    <div class="row">
                        <div class="col-xs-12 col-sm-4 col-lg-4 clgfrmimgltst5 clgletstbotom7 padding-left">
                            <div class="col-xs-12 col-sm-12 col-lg-12 clgletstbotom7 " style="padding-right: 0px; padding-left:29px; ">		  
                                <div id="c-slot-1" data-box-id="215" class="squ-5 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
                            </div>
                            <div class="col-xs-12 col-sm-12 col-lg-12 clgletstbotom7 " style="padding-right: 0px; padding-left:29px; ">		  
                                <div id="c-slot-2" data-box-id="216" class="ap-2 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-4 col-lg-4 clgfrmimgltst5 padding-left">
                            <div class="col-xs-12 col-sm-6 col-lg-6  clgletstbotom7 padding-left padding0 pad-rit" >
                                <div id="c-slot-3" data-box-id="217" class="ap-1 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
                            </div>
                            <div class="col-xs-12 col-sm-6 col-lg-6 clgletstbotom7 padding-left padding0 pad-lft">
                                <div id="c-slot-4" data-box-id="218" class="ap-1 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
                            </div>
                            <div class="col-xs-12 col-sm-12 col-lg-12 clgletstbotom7  padding0">
                                <div id="c-slot-5" data-box-id="219" class="sq-3 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
                            </div>
                            <div class="col-xs-12 col-sm-6 col-lg-6  clgletstbotom7 padding-left padding0 pad-rit" >
                                <div id="c-slot-6" data-box-id="220" class="ap-4 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
                            </div>
                            <div class="col-xs-12 col-sm-6 col-lg-6 clgletstbotom7 padding-left padding0 pad-lft">
                                <div id="c-slot-7" data-box-id="221" class="ap-4 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-4 col-lg-4 clgfrmimgltst5 clgletstbotom7 padding-left" style=" padding:0px; ">
                            <div class="col-xs-12 col-sm-12 col-lg-12  clgletstbotom7 padding-left" style="padding:0px; padding-right:29px;">
                                <div id="c-slot-8" data-box-id="222" class="ap-2 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
                            </div>
                            <div class="col-xs-12 col-sm-12 col-lg-12  clgletstbotom7 padding-left " style="padding:0px; padding-right:29px;">	  
                                <div id="c-slot-9" data-box-id="223" class="squ-5 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="clearfix"></div>
                <span id="page_2">
                    <div placeholder="Dein Text hier" id="c-text" class="seconds">Enter text here (Optional)</div>
                </span>
            </div>
            <div class="clearfix hidden-lg" style="height:20px;"></div>
        </div>
    </div>         
</div>
<div id="get_slot_id"></div>
<!--Frame Div Ends-->