<style>
/*apertures-9 css*/
.ape-9-48 {
    background: rgb(238, 243, 250) none repeat scroll 0 0;
    cursor: pointer;
    height: 143px;
}
#c-designer {
    background: rgb(226, 226, 226) none repeat scroll 0 0;
    margin-bottom: 60px;
    min-height: 882px;
    padding: 1px;
    width: 100%;
}
#c-designer-layout-wrapper {
    float: left;
    height: 578px;
    padding: 130px;
    position: relative;
    width: 100%;
}
#c-designer-layout-wrapper {
    float: left;
    height: 578px;
    padding: 6px 130px 130px;
    position: relative;
    width: 100%;
}
.clgfrmimgltst5 {
    padding-right: 8px;
}
.clgletstbotom7 {
    margin-bottom: 8px;
}

/*square-4css end*/
</style>
<!--Frame Div Starts-->
<div class="col-xs-12 col-sm-8 col-md-8"> 
    <ul id="c-designer-header-tools">
        <li>Auto-fill<span class="icon-magic"></span></li>
        <li>Edit text<span class="icon-text-height"></span></li>
        <li>Clear collage<span class="icon-eraser"></span></li>
        <li class="pull-right"><a href="../index.php" style="color:#fff;">Change template<span class="icon-th"></span></a></li>
    </ul>
    <div id="c-designer">
	<div id="c-designer-layout-wrapper">
    <div id="c-layout" class="c-layout-43-3-h-txt-vacation1 col-xs-12 col-sm-12 col-lg-12 clgframboxvr2 paddingadjust" >
	  <div class="col-xs-12 col-sm-12  col-lg-12 ">
        <div class="row">
          <div  class=" col-xs-12 col-sm-8 col-lg-8 clgfrmimgltst5 clgletstbotom7 padding-left ">
            <div id="c-slot-1" data-box-id="251" class="ape-9-48 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
          </div>
           <div  class=" col-xs-12 col-sm-4 col-lg-4 clgfrmimgltst5 clgletstbotom7 padding-left ">
            <div id="c-slot-2" data-box-id="252" class="ape-9-48 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
          </div>
        </div>
      </div>
	  <div class="col-xs-12 col-sm-12  col-lg-12 ">
        <div class="row">
          <div  class=" col-xs-12 col-sm-4 col-lg-4 clgfrmimgltst5 clgletstbotom7 padding-left ">
            <div id="c-slot-3" data-box-id="253" class="ape-9-48 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
          </div>
           <div  class=" col-xs-12 col-sm-4 col-lg-4 clgfrmimgltst5 clgletstbotom7 padding-left ">
            <div id="c-slot-4" data-box-id="254" class="ape-9-48 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
          </div>
		   <div  class=" col-xs-12 col-sm-4 col-lg-4 clgfrmimgltst5 clgletstbotom7 padding-left ">
            <div id="c-slot-5" data-box-id="255" class="ape-9-48 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
          </div>
        </div>
      </div>
	  <div class="col-xs-12 col-sm-12  col-lg-12 ">
        <div class="row">
          <div  class=" col-xs-12 col-sm-4 col-lg-4 clgfrmimgltst5 clgletstbotom7 padding-left ">
            <div id="c-slot-6" data-box-id="256" class="ape-9-48 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
          </div>
           <div  class=" col-xs-12 col-sm-4 col-lg-4 clgfrmimgltst5 clgletstbotom7 padding-left ">
            <div id="c-slot-7" data-box-id="257" class="ape-9-48 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
          </div>
		   <div  class=" col-xs-12 col-sm-4 col-lg-4 clgfrmimgltst5 clgletstbotom7 padding-left ">
            <div id="c-slot-8" data-box-id="258" class="ape-9-48 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
          </div>
        </div>
      </div>
	  <div class="col-xs-12 col-sm-12  col-lg-12 ">
        <div class="row">
		<div  class=" col-xs-12 col-sm-4 col-lg-4 clgfrmimgltst5 clgletstbotom7 padding-left ">
            <div id="c-slot-9" data-box-id="259" class="ape-9-48 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
          </div>
          <div  class=" col-xs-12 col-sm-8 col-lg-8 clgfrmimgltst5 clgletstbotom7 padding-left ">
            <div id="c-slot-10" data-box-id="260" class="ape-9-48 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
          </div>
        </div>
      </div>
      <div class="clearfix"></div>
	  <span id="page_2">
		<div placeholder="Dein Text hier" id="c-text" class="seconds">Enter text here (Optional)</div>
	  </span>
    </div>
    <div class="clearfix hidden-lg" style="height:20px;"></div>
  </div>
</div>         
</div>
<div id="get_slot_id"></div>
<!--Frame Div Ends-->