<style>
    /*10-apertures-mixed css*/
    .apertures-mixed-50{
        background:#eef3fa;
        cursor:pointer;
        height: 115px;	
    }
    .aper-m-50{
        background:#eef3fa;
        cursor:pointer;
        height: 55px;	
    }
    .apertures-mixe-50{
        background:#eef3fa;
        cursor:pointer;
        height: 115px;	
    }
    .apertures-mi-50{
        background:#eef3fa;
        cursor:pointer;
        height: 178px;	
    }
    .padding0{
        padding:0px;
    }
    .clgfrmimgltst5 {
        padding-right: 8px;
    }
    .clgletstbotom7 {
        margin-bottom: 8px;
    }
    #c-designer {
    background: #e2e2e2 none repeat scroll 0 0;
    margin-bottom: 60px;
    min-height: 570px;
    padding: 50px;
    width: 100%;
    }
    .clgframboxvr2 {
    background: #fff none repeat scroll 0 0;
    display: block;
    float: none;
    margin: 0 auto;
    padding: 50px 18px 30px;
    }
    /*square-4css end*/
</style>
<!--Frame Div Starts-->
<div class="col-xs-12 col-sm-8 col-md-8"> 
    <ul id="c-designer-header-tools">
        <li>Auto-fill<span class="icon-magic"></span></li>
        <li>Edit text<span class="icon-text-height"></span></li>
        <li>Clear collage<span class="icon-eraser"></span></li>
        <li class="pull-right"><a href="../index.php" style="color:#fff;">Change template<span class="icon-th"></span></a></li>
    </ul>
    <div id="c-designer">
        <div id="c-designer-layout-wrapper">
            <div id="c-layout" class="c-layout-43-3-h-txt-vacation1 col-xs-12 col-sm-12 col-lg-12 clgframboxvr2 paddingadjust" >
                <div class="col-xs-12 col-sm-12  col-lg-12 ">
                    <div class="row">
                        <div  class=" col-xs-12 col-sm-4 col-lg-4 clgfrmimgltst5  padding-left "style="padding-left: 42px;">
                            <div class="col-xs-12 col-sm-12  col-lg-12  clgletstbotom7  padding0">
                                <div id="c-slot-1" data-box-id="281" class="apertures-mi-50 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
                            </div>
                            <div class="col-xs-12 col-sm-12  col-lg-12  clgletstbotom7  padding0">
                                <div id="c-slot-2" data-box-id="282" class="apertures-mixe-50 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
                            </div>
                        </div>
                        <div  class=" col-xs-12 col-sm-2 col-lg-2 clgfrmimgltst5  padding-left ">
                            <div class="col-xs-12 col-sm-12  col-lg-12  clgletstbotom7  padding0">
                                <div id="c-slot-3" data-box-id="283" class="apertures-mixed-50 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
                            </div>
                            <div class="col-xs-12 col-sm-12  col-lg-12  clgletstbotom7  padding0">
                                <div id="c-slot-4" data-box-id="284" class="aper-m-50 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
                            </div>
                            <div class="col-xs-12 col-sm-12  col-lg-12  clgletstbotom7  padding0">
                                <div id="c-slot-5" data-box-id="285" class="apertures-mixed-50 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
                            </div>
                        </div>
                        <div  class=" col-xs-12 col-sm-2 col-lg-2 clgfrmimgltst5  padding-left ">
                            <div class="col-xs-12 col-sm-12  col-lg-12  clgletstbotom7  padding0">
                                <div id="c-slot-6" data-box-id="286" class="apertures-mixed-50 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
                            </div>
                            <div class="col-xs-12 col-sm-12  col-lg-12  clgletstbotom7  padding0">
                                <div id="c-slot-7" data-box-id="287" class="aper-m-50 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
                            </div>
                            <div class="col-xs-12 col-sm-12  col-lg-12  clgletstbotom7  padding0">
                                <div id="c-slot-8" data-box-id="288" class="apertures-mixed-50 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
                            </div>
                        </div>
                        <div  class=" col-xs-12 col-sm-4 col-lg-4 clgfrmimgltst5  padding-left " style="padding-right: 42px;">
                            <div class="col-xs-12 col-sm-12  col-lg-12  clgletstbotom7  padding0">
                                <div id="c-slot-9" data-box-id="289" class="apertures-mixe-50 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
                            </div>
                            <div class="col-xs-12 col-sm-12  col-lg-12  clgletstbotom7  padding0">
                                <div id="c-slot-10" data-box-id="290" class="apertures-mi-50 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="clearfix"></div>
                <span id="page_2">
                    <div placeholder="Dein Text hier" id="c-text" class="seconds">Enter text here (Optional)</div>
                </span>
            </div>
            <div class="clearfix hidden-lg" style="height:20px;"></div>
        </div>
    </div>         
</div>
<div id="get_slot_id"></div>
<!--Frame Div Ends-->