
<!--Frame Div Starts-->
<div class="col-xs-12 col-sm-8 col-md-8  "> 
    <ul id="c-designer-header-tools">
        <li>Auto-fill<span class="icon-magic"></span></li>
        <li class="c-text-2">Edit text<span class="icon-text-height"></span></li>
        <li>Clear collage<span class="icon-eraser"></span></li>
        <li class="pull-right"><a href="../index.php" style="color:#fff;">Change template<span class="icon-th"></span></a></li>
    </ul>
    <div class="cf livemode" id="designer">
        <div id="c-designer-layout-wrapper">
            <div  id="c-layout"  class="c-layout-43-3-h-txt-vacation1 col-xs-12 col-sm-6 clgframboxvr2">
                <div id="c-slot-1" data-box-id="14" class="col-xs-12 col-sm-12 col-lg-12 clgfrminrimgs padding my_image" style="overflow:hidden;">
                    <div id="c-slot-1" class="c-layout-slot rect-v pos-1 ui-droppable frm2ht"></div>
                </div>
                <div id="c-slot-2" data-box-id="15" class="col-xs-12 col-sm-12 col-lg-12 clgfrminrimgs my_image padding" style="overflow:hidden;">
                    <div id="c-slot-2" class="c-layout-slot rect-v pos-2 ui-droppable frm2ht"></div>
                </div>
                <div id="c-slot-3" data-box-id="16" class=" col-xs-12 col-sm-12 col-lg-12 clgfrminrimgs my_image padding" style="overflow:hidden;">
                    <div id="c-slot-3" class="c-layout-slot rect-v pos-3 ui-droppable frm2ht"></div>
                </div> 
                <div id="c-slot-4" data-box-id="17" class="col-xs-12 col-sm-12 col-lg-12 clgfrminrimgs my_image padding" style="overflow:hidden;">
                    <div id="c-slot-4" class="c-layout-slot rect-v pos-2 ui-droppable frm2ht"></div>
                </div>
                          <div class="clearfix"></div>

                <span id="page_2">
                    <div placeholder="Dein Text hier" id="c-text" class="seconds">Enter text here (Optional)</div>
                </span>
            </div>
        </div>
    </div>
</div>
<div id="c-designer-modal">
    <div id="c-designer-modal-content">
        <h4>Crop image<span class="icon-move"></span></h4>
        <div id="c-designer-modal-crop" style="width: 280px; height: 430px;">
            <img alt="modal image" id="c-designer-modal-img" width="280" height="430" src="" style="width: 280px; height: 430px; display: inline; visibility: visible;">
        </div>
        <span id="c-designer-modal-crop-confirm" class="btn btn-green"><span>Apply</span> <i class="glyphicon glyphicon-ok"></i></span> 
    </div>
</div>
<div id="get_slot_id"></div>
<!--Frame Div Ends-->

