<style>
    /*9-mixed apertures css*/
    .apertures-9-mixed-53{
        background: rgb(238, 243, 250) none repeat scroll 0 0;
        cursor: pointer;
        height: 120px;
    }
    .apertures-9-mixed-53-new{
        background: rgb(238, 243, 250) none repeat scroll 0 0;
        cursor: pointer;
        height: 57px;
    }
    .paddingadjust{
        padding: 51px 50px 30px 55px !important;
    }
    .clgfrmimgltst5 {
        padding-right: 8px;
    }
    .clgletstbotom7 {
        margin-bottom: 8px;
    }
    /*square-4css end*/
</style>
<!--Frame Div Starts-->
<div class="col-xs-12 col-sm-8 col-md-8"> 
    <ul id="c-designer-header-tools">
        <li>Auto-fill<span class="icon-magic"></span></li>
        <li>Edit text<span class="icon-text-height"></span></li>
        <li>Clear collage<span class="icon-eraser"></span></li>
        <li class="pull-right"><a href="../index.php" style="color:#fff;">Change template<span class="icon-th"></span></a></li>
    </ul>
    <div id="c-designer">
        <div id="c-designer-layout-wrapper">
            <div id="c-layout" class="c-layout-43-3-h-txt-vacation1 col-xs-12 col-sm-12 col-lg-12 clgframboxvr2 paddingadjust" >
                <div class="col-xs-12 col-sm-12  col-lg-12 ">
                    <div class="row">
                        <div  class=" col-xs-12 col-sm-2 col-lg-2 clgfrmimgltst5 clgletstbotom7 padding-left ">
                            <div id="c-slot-1" data-box-id="343" class="apertures-9-mixed-53 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
                        </div>
                        <div  class=" col-xs-12 col-sm-2 col-lg-2 clgfrmimgltst5 clgletstbotom7 padding-left ">
                            <div id="c-slot-2" data-box-id="344" class="apertures-9-mixed-53 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
                        </div>

                        <div  class=" col-xs-12 col-sm-4 col-lg-4 clgfrmimgltst5 clgletstbotom7 padding-left ">
                            <div id="c-slot-3" data-box-id="345" class="apertures-9-mixed-53 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
                        </div>

                        <div  class=" col-xs-12 col-sm-2 col-lg-2 clgfrmimgltst5 clgletstbotom7 padding-left ">
                            <div id="c-slot-4" data-box-id="346" class="apertures-9-mixed-53-new c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden; margin-bottom:7px;"></div>

                            <div id="c-slot-5" data-box-id="347" class="apertures-9-mixed-53-new c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
                        </div>

                        <div  class=" col-xs-12 col-sm-2 col-lg-2 clgfrmimgltst5 clgletstbotom7 padding-left ">
                            <div id="c-slot-6" data-box-id="348" class="apertures-9-mixed-53 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
                        </div>
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12  col-lg-12 ">
                    <div class="row">
                        <div  class=" col-xs-12 col-sm-2 col-lg-2 clgfrmimgltst5 clgletstbotom7 padding-left ">
                            <div id="c-slot-7" data-box-id="349" class="apertures-9-mixed-53 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
                        </div>

                        <div  class=" col-xs-12 col-sm-2 col-lg-2 clgfrmimgltst5 clgletstbotom7 padding-left ">
                            <div id="c-slot-8" data-box-id="350" class="apertures-9-mixed-53-new c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden; margin-bottom:7px;"></div>

                            <div id="c-slot-9" data-box-id="351" class="apertures-9-mixed-53-new c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
                        </div>

                        <div  class=" col-xs-12 col-sm-4 col-lg-4 clgfrmimgltst5 clgletstbotom7 padding-left ">
                            <div id="c-slot-10" data-box-id="352" class="apertures-9-mixed-53 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
                        </div>

                        <div  class=" col-xs-12 col-sm-2 col-lg-2 clgfrmimgltst5 clgletstbotom7 padding-left ">
                            <div id="c-slot-11" data-box-id="353" class="apertures-9-mixed-53 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
                        </div>

                        <div  class=" col-xs-12 col-sm-2 col-lg-2 clgfrmimgltst5 clgletstbotom7 padding-left ">
                            <div id="c-slot-12" data-box-id="354" class="apertures-9-mixed-53 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
                        </div>
                    </div>
                </div>
                <div class="clearfix"></div>
                <span id="page_2">
                    <div placeholder="Dein Text hier" id="c-text" class="seconds">Enter text here (Optional)</div>
                </span>
            </div>
            <div class="clearfix hidden-lg" style="height:20px;"></div>
        </div>
    </div>         
</div>
<div id="get_slot_id"></div>
<!--Frame Div Ends-->