<style>
    /*11-apertures-mixed css*/
    .apertures-mixed-59{
        background:#eef3fa;
        cursor:pointer;
        height: 126px;	
    }
    .padding0 {
        padding:0;
    }
    .clgfrmimgltst5 {
        padding-right: 6px;
    }
    .clgletstbotom7 {
        margin-bottom: 10px;
    }

    .paddingadjust{
        padding: 51px 42px 30px 54px !important;
    }
    #c-designer {
    background: #e2e2e2 none repeat scroll 0 0;
    margin-bottom: 60px;
    min-height: 760px;
    padding: 44px;
    width: 100%;
    }
    /*square-4css end*/
</style>
<!--Frame Div Starts-->
<div class="col-xs-12 col-sm-8 col-md-8"> 
    <ul id="c-designer-header-tools">
        <li>Auto-fill<span class="icon-magic"></span></li>
        <li>Edit text<span class="icon-text-height"></span></li>
        <li>Clear collage<span class="icon-eraser"></span></li>
        <li class="pull-right"><a href="../index.php" style="color:#fff;">Change template<span class="icon-th"></span></a></li>
    </ul>
    <div id="c-designer">
        <div id="c-designer-layout-wrapper">
            <div id="c-layout" class="c-layout-43-3-h-txt-vacation1 col-xs-12 col-sm-12 col-lg-12 clgframboxvr2 paddingadjust" >
                <div class="col-xs-12 col-sm-12  col-lg-12 ">
                    <div class="row">
                        <div class="col-xs-12 col-sm-5  col-lg-5 padding0 clgfrmimgltst5  rr1 " style="padding-left: 4px;">
                            <div  class="  col-xs-12 col-sm-12 col-lg-12 clgletstbotom7 padding-left padding0 ">
                                <div id="c-slot-1" data-box-id="367" class="apertures-mixed-59 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
                            </div>
                            <div  class="  col-xs-12 col-sm-6 col-lg-6 clgletstbotom7 clgfrmimgltst5   padding-left padding0" style="padding-right: 3px;">
                                <div id="c-slot-4" data-box-id="370" class="apertures-mixed-59  c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
                            </div>
                            <div  class="  col-xs-12 col-sm-6 col-lg-6 clgletstbotom7 padding-left padding0" style="padding-left: 3px;">
                                <div id="c-slot-5" data-box-id="371" class="apertures-mixed-59  c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
                            </div>
                            <div  class="  col-xs-12 col-sm-12 col-lg-12 clgletstbotom7 padding-left padding0 ">
                                <div id="c-slot-9" data-box-id="375" class="apertures-mixed-59 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-2  col-lg-2  padding0 rr2  ">
                            <div  class="  col-xs-12 col-sm-12 col-lg-12  clgletstbotom7 padding-left padding0  ">
                                <div id="c-slot-2" data-box-id="368" class="apertures-mixed-59 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
                            </div>
                            <div  class="  col-xs-12 col-sm-12 col-lg-12 clgletstbotom7 padding-left padding0 ">
                                <div id="c-slot-6" data-box-id="372" class="apertures-mixed-59 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
                            </div>
                            <div  class="  col-xs-12 col-sm-12 col-lg-12 clgletstbotom7 padding-left padding0  ">
                                <div id="c-slot-10" data-box-id="376" class="apertures-mixed-59 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-5  col-lg-5  padding0 "  style="padding-left: 6px; padding-right: 2px;">
                            <div  class="  col-xs-12 col-sm-12 col-lg-12 clgletstbotom7 padding-left padding0 ">
                                <div id="c-slot-3" data-box-id="369" class="apertures-mixed-59 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
                            </div>
                            <div  class="  col-xs-12 col-sm-6 col-lg-6 clgletstbotom7 clgfrmimgltst5   padding-left padding0" style="padding-right: 3px;">
                                <div id="c-slot-7" data-box-id="373" class="apertures-mixed-59  c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
                            </div>
                            <div  class="  col-xs-12 col-sm-6 col-lg-6 clgletstbotom7 padding-left padding0"style="padding-left: 2px;">
                                <div id="c-slot-8" data-box-id="374" class="apertures-mixed-59  c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
                            </div>
                            <div  class="  col-xs-12 col-sm-12 col-lg-12 clgletstbotom7 padding-left padding0 ">
                                <div id="c-slot-11" data-box-id="377" class="apertures-mixed-59 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="clearfix"></div>
                <span id="page_2">
                    <div placeholder="Dein Text hier" id="c-text" class="seconds">Enter text here (Optional)</div>
                </span>
            </div>
            <div class="clearfix hidden-lg" style="height:20px;"></div>
        </div>
    </div>         
</div>
<div id="get_slot_id"></div>
<!--Frame Div Ends-->