
<style>
.mixed-apertures-4{
	background:#eef3fa;
	cursor:pointer;
	height:285px;	

}
.mixed-apertures-4sm{
	background:#eef3fa;
	cursor:pointer;
	height:250px;	

}
.paddingadjust{
	padding:50px 32px 32px 50px !important;
}
#c-designer {
    background: #e2e2e2 none repeat scroll 0 0;
    margin-bottom: 60px;
    min-height: 790px;
    padding: 1px;
    width: 100%;
}
#page_2 {
    color: #000000;
    font-family: "Open Sans","sans-serif";
    font-size: 22px;
    text-align: center;
    position: relative;
    top: 17px;
}
</style>
<!--Frame Div Starts-->

<div class="col-xs-12 col-sm-8 col-md-8"> 
    <ul id="c-designer-header-tools">
        <li>Auto-fill<span class="icon-magic"></span></li>
        <li>Edit text<span class="icon-text-height"></span></li>
        <li>Clear collage<span class="icon-eraser"></span></li>
        <li class="pull-right"><a href="../index.php" style="color:#fff;">Change template<span class="icon-th"></span></a></li>
    </ul>
	<div id="c-designer">
	   <div id="c-designer-layout-wrapper">
		<div id="c-layout" class="c-layout-43-3-h-txt-vacation1 col-xs-12 col-sm-12 col-lg-12 clgframboxvr2 paddingadjust" >
		  <div class="col-xs-12 col-sm-12  col-lg-12">
			<div class="row">
			  <div  class=" col-xs-12 col-sm-12 col-lg-12 clgfrmimgltst5 clgletstbotom7 padding-left">
				<div id="c-slot-1" data-box-id="18" class="mixed-apertures-4 c-layout-slot rect-v pos-1 ui-droppable frm2ht" style="overflow:hidden;"></div>
			  </div>
			</div>
		  </div>
		  <div class="col-xs-12 col-sm-12  col-lg-12 ">
			<div class="row">
			  <div class="col-xs-12 col-sm-4 col-lg-4 clgfrmimgltst5 padding-left">
				<div id="c-slot-2" data-box-id="19" class="mixed-apertures-4sm c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
			  </div>
			  <div class="col-xs-12 col-sm-4 col-lg-4 clgfrmimgltst5 padding-left">
				<div id="c-slot-3" data-box-id="20" class="mixed-apertures-4sm c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
			  </div>
			  <div class="col-xs-12 col-sm-4 col-lg-4 clgfrmimgltst5 padding-left">
				<div id="c-slot-4" data-box-id="21" class="mixed-apertures-4sm c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
			  </div>
			</div>
			<span id="page_2">
                <div placeholder="Dein Text hier" id="c-text" class="seconds">Enter text here (Optional)</div>
            </span>
		  </div>
		  <div class="clearfix"></div>
		</div>
		<div class="clearfix hidden-lg" style="height:20px;"></div>
	  </div>
	</div>         
</div>
<div id="get_slot_id"></div>
<!--Frame Div Ends-->