<style>
/*14-apertures css*/
.apertures-mi-65{
	background:#eef3fa;
	cursor:pointer;
	height: 55px;	
}
.mixed-apertures-65{
	background:#eef3fa;
	cursor:pointer;
	height: 120px;	
}
.mixed-a-55{
	background:#eef3fa;
	cursor:pointer;
	height: 122px;	
}
.padding0{
	padding:0px;
}
.clgfrmimgltst5 {
    padding-right: 8px;
}
.clgletstbotom7 {
    margin-bottom: 8px;
}
.paddingadjust{
    padding: 51px 50px 30px 55px !important;
}
/*square-4css end*/
</style>
<!--Frame Div Starts-->

<div class="col-xs-12 col-sm-8 col-md-8"> 
    <ul id="c-designer-header-tools">
        <li>Auto-fill<span class="icon-magic"></span></li>
        <li>Edit text<span class="icon-text-height"></span></li>
        <li>Clear collage<span class="icon-eraser"></span></li>
        <li class="pull-right"><a href="../index.php" style="color:#fff;">Change template<span class="icon-th"></span></a></li>
    </ul>
    <div id="c-designer">
        <div id="c-designer-layout-wrapper">
    <div id="c-layout" class="c-layout-43-3-h-txt-vacation1 col-xs-12 col-sm-12 col-lg-12 clgframboxvr2 paddingadjust" >

         <div class="col-xs-12 col-sm-12  col-lg-12 ">
        <div class="row">
          <div  class=" col-xs-12 col-sm-2 col-lg-2 clgfrmimgltst5  padding-left ">
		  
			<div class="col-xs-12 col-sm-12  col-lg-12  clgletstbotom7  padding0">
            <div id="c-slot-1" data-box-id="426" class="mixed-apertures-65 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
			</div>
			<div class="col-xs-12 col-sm-12  col-lg-12  clgletstbotom7  padding0">
            <div id="c-slot-2" data-box-id="427" class="apertures-mi-65 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
			</div>
			<div class="col-xs-12 col-sm-12  col-lg-12  clgletstbotom7  padding0">
            <div id="c-slot-3" data-box-id="428" class="apertures-mi-65 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
			</div>
          </div>
		  
          <div  class=" col-xs-12 col-sm-2 col-lg-2 clgfrmimgltst5  padding-left ">
		  
			<div class="col-xs-12 col-sm-12  col-lg-12  clgletstbotom7  padding0">
            <div id="c-slot-4" data-box-id="429" class="mixed-apertures-65 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
			</div>
			<div class="col-xs-12 col-sm-12  col-lg-12  clgletstbotom7  padding0">
            <div id="c-slot-5" data-box-id="430" class="apertures-mi-65 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
			</div>
			<div class="col-xs-12 col-sm-12  col-lg-12  clgletstbotom7  padding0">
            <div id="c-slot-6" data-box-id="431" class="apertures-mi-65 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
			</div>
          </div>
		  
		  
		    <div  class=" col-xs-12 col-sm-4 col-lg-4 clgfrmimgltst5  padding-left ">
		  <div class="col-xs-12 col-sm-12  col-lg-12  clgletstbotom7  padding0">
            <div id="c-slot-7" data-box-id="432" class="mixed-apertures-65 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
			</div>
			<div class="col-xs-12 col-sm-12  col-lg-12  clgletstbotom7  padding0">
            <div id="c-slot-8" data-box-id="433" class="mixed-apertures-65 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
			</div>
          </div>
		  
		  
         <div  class=" col-xs-12 col-sm-2 col-lg-2 clgfrmimgltst5  padding-left ">
		 
			 <div class="col-xs-12 col-sm-12  col-lg-12  clgletstbotom7  padding0">
            <div id="c-slot-9" data-box-id="434" class="apertures-mi-65 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
			</div>
			 <div class="col-xs-12 col-sm-12  col-lg-12  clgletstbotom7  padding0">
            <div id="c-slot-10" data-box-id="435" class="apertures-mi-65 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
			</div>
						<div class="col-xs-12 col-sm-12  col-lg-12  clgletstbotom7  padding0">
            <div id="c-slot-11" data-box-id="436" class="mixed-apertures-65 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
			</div>
          </div>
         <div  class=" col-xs-12 col-sm-2 col-lg-2 clgfrmimgltst5  padding-left ">
		 			 <div class="col-xs-12 col-sm-12  col-lg-12  clgletstbotom7  padding0">
            <div id="c-slot-12" data-box-id="437" class="apertures-mi-65 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
			</div>

			 <div class="col-xs-12 col-sm-12  col-lg-12  clgletstbotom7  padding0">
            <div id="c-slot-13" data-box-id="438" class="apertures-mi-65 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
			</div>
						<div class="col-xs-12 col-sm-12  col-lg-12  clgletstbotom7  padding0">
            <div id="c-slot-14" data-box-id="439" class="mixed-apertures-65 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
			</div>
          </div>
        </div>
      </div>
      <div class="clearfix"></div>
	  <span id="page_2">
		<div placeholder="Dein Text hier" id="c-text" class="seconds">Enter text here (Optional)</div>
	  </span>
    </div>
    <div class="clearfix hidden-lg" style="height:20px;"></div>
  </div>
</div>         
</div>
<div id="get_slot_id"></div>
<!--Frame Div Ends-->