<style>
    /*14-apertures-upright css*/
    .mixed-apertures-66{
        background: rgb(238, 243, 250) none repeat scroll 0 0;
        cursor: pointer;
        height: 195px;
    }
    .apertures-upright-66 {
        background: rgb(238, 243, 250) none repeat scroll 0 0;
        cursor: pointer;
        height: 100px;
    }
    #c-designer-layout-wrapper {
        float: left;
        height: 578px;
        padding: 6px 100px 79px;
        position: relative;
        width: 100%;
    }
    #c-designer {
        background: rgb(226, 226, 226) none repeat scroll 0 0;
        margin-bottom: 60px;
        min-height: 1080px;
        padding: 28px;
        width: 100%;
    }
    .clgfrmimgltst5 {
        padding-right: 8px;
    }
    .clgletstbotom7 {
        margin-bottom: 8px;
    }

    /*square-4css end*/
</style>
<!--Frame Div Starts-->
<div class="col-xs-12 col-sm-8 col-md-8"> 
    <ul id="c-designer-header-tools">
        <li>Auto-fill<span class="icon-magic"></span></li>
        <li>Edit text<span class="icon-text-height"></span></li>
        <li>Clear collage<span class="icon-eraser"></span></li>
        <li class="pull-right"><a href="../index.php" style="color:#fff;">Change template<span class="icon-th"></span></a></li>
    </ul>
    <div id="c-designer">
        <div id="c-designer-layout-wrapper">
            <div id="c-layout" class="c-layout-43-3-h-txt-vacation1 col-xs-12 col-sm-12 col-lg-12 clgframboxvr2 paddingadjust" >
                <div class="col-xs-12 col-sm-12  col-lg-12 ">
                    <div class="row">
                        <div  class=" col-xs-12 col-sm-6 col-lg-6 clgfrmimgltst5 clgletstbotom7 padding-left ">
                            <div id="c-slot-1" data-box-id="440" class="apertures-upright-66  c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
                        </div>
                        <div  class=" col-xs-12 col-sm-3 col-lg-3 clgfrmimgltst5 clgletstbotom7 padding-left ">
                            <div id="c-slot-2" data-box-id=441 class="apertures-upright-66  c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
                        </div>

                        <div  class=" col-xs-12 col-sm-3 col-lg-3 clgfrmimgltst5 clgletstbotom7 padding-left ">
                            <div id="c-slot-3" data-box-id="442" class="apertures-upright-66  c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
                        </div>
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12  col-lg-12 ">
                    <div class="row">
                        <div  class=" col-xs-12 col-sm-6 col-lg-6 clgfrmimgltst5 clgletstbotom7 padding-left ">
                            <div id="c-slot-4" data-box-id="443" class="apertures-upright-66  c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
                        </div>

                        <div  class=" col-xs-12 col-sm-3 col-lg-3 clgfrmimgltst5 clgletstbotom7 padding-left ">
                            <div id="c-slot-5" data-box-id="444" class="apertures-upright-66  c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
                        </div>
                        <div  class=" col-xs-12 col-sm-3 col-lg-3 clgfrmimgltst5 clgletstbotom7 padding-left ">
                            <div id="c-slot-6" data-box-id="445" class="apertures-upright-66  c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
                        </div>
                    </div>
                </div>

                <div class="col-xs-12 col-sm-12  col-lg-12 ">
                    <div class="row">

                        <div  class=" col-xs-12 col-sm-6 col-lg-6 clgfrmimgltst5 clgletstbotom7 padding-left ">
                            <div id="c-slot-7" data-box-id="446" class="mixed-apertures-66 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
                        </div>
                        <div  class=" col-xs-12 col-sm-6 col-lg-6 clgfrmimgltst5 clgletstbotom7 padding-left ">
                            <div id="c-slot-8" data-box-id="447" class="mixed-apertures-66 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
                        </div>
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12  col-lg-12 ">
                    <div class="row">
                        <div  class=" col-xs-12 col-sm-3 col-lg-3 clgfrmimgltst5 clgletstbotom7 padding-left ">
                            <div id="c-slot-9" data-box-id="448" class="apertures-upright-66  c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
                        </div>
                        <div  class=" col-xs-12 col-sm-3 col-lg-3 clgfrmimgltst5 clgletstbotom7 padding-left ">
                            <div id="c-slot-10" data-box-id="449" class="apertures-upright-66  c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
                        </div>
                        <div  class=" col-xs-12 col-sm-6 col-lg-6 clgfrmimgltst5 clgletstbotom7 padding-left ">
                            <div id="c-slot-11" data-box-id="450" class="apertures-upright-66  c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
                        </div>
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12  col-lg-12 ">
                    <div class="row">
                        <div  class=" col-xs-12 col-sm-3 col-lg-3 clgfrmimgltst5 clgletstbotom7 padding-left ">
                            <div id="c-slot-12" data-box-id="451" class="apertures-upright-66  c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
                        </div>
                        <div  class=" col-xs-12 col-sm-3 col-lg-3 clgfrmimgltst5 clgletstbotom7 padding-left ">
                            <div id="c-slot-13" data-box-id="452" class="apertures-upright-66 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
                        </div>
                        <div  class=" col-xs-12 col-sm-6 col-lg-6 clgfrmimgltst5 clgletstbotom7 padding-left ">
                            <div id="c-slot-14" data-box-id="453" class="apertures-upright-66  c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
                        </div>
                    </div>
                </div>
                <div class="clearfix"></div>
                <span id="page_2">
                    <div placeholder="Dein Text hier" id="c-text" class="seconds">Enter text here (Optional)</div>
                </span>
            </div>
            <div class="clearfix hidden-lg" style="height:20px;"></div>
        </div>
    </div>         
</div>
<div id="get_slot_id"></div>
<!--Frame Div Ends-->