<style>
/*16-apertures-upright css*/
.apertures-upright-69{
	background:#eef3fa;
	cursor:pointer;
	height: 85px;	
}
.mixed-apertures-69{
	background:#eef3fa;
	cursor:pointer;
	height: 178px;	
}
.mixed-a-69{
	background:#eef3fa;
	cursor:pointer;
	height: 178px;	
}
.aperturerrss {
    background: rgb(238, 243, 250) none repeat scroll 0 0;
    cursor: pointer;
    height: 131px;
}
.padding0{
	padding:0px;
}
.clgfrmimgltst5 {
    padding-right: 8px;
}
.clgletstbotom7 {
    margin-bottom: 8px;
}
.paddingadjust{
    padding: 51px 50px 30px 55px !important;
}
/*square-4css end*/
</style>
<!--Frame Div Starts-->
<div class="col-xs-12 col-sm-8 col-md-8"> 
    <ul id="c-designer-header-tools">
        <li>Auto-fill<span class="icon-magic"></span></li>
        <li>Edit text<span class="icon-text-height"></span></li>
        <li>Clear collage<span class="icon-eraser"></span></li>
        <li class="pull-right"><a href="../index.php" style="color:#fff;">Change template<span class="icon-th"></span></a></li>
    </ul>
    <div id="c-designer">
        <div id="c-designer-layout-wrapper">
    <div id="c-layout" class="c-layout-43-3-h-txt-vacation1 col-xs-12 col-sm-12 col-lg-12 clgframboxvr2 paddingadjust" >

         <div class="col-xs-12 col-sm-12  col-lg-12 ">
        <div class="row">
		
         <div  class=" col-xs-12 col-sm-3 col-lg-3 clgfrmimgltst5  padding-left ">
		  <div class="col-xs-12 col-sm-12  col-lg-12  clgletstbotom7  padding0">
            <div id="c-slot-1" data-box-id="486" class="apertures-upright-69 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
			</div>
			<div class="col-xs-12 col-sm-12  col-lg-12  clgletstbotom7  padding0">
            <div id="c-slot-2" data-box-id="487" class="apertures-upright-69 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
			</div>
          </div>
          <div  class=" col-xs-12 col-sm-3 col-lg-3 clgfrmimgltst5  padding-left ">
		  <div class="col-xs-12 col-sm-12  col-lg-12  clgletstbotom7  padding0">
            <div id="c-slot-3" data-box-id="488" class="mixed-a-69 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
			</div>
          </div>
		    <div  class=" col-xs-12 col-sm-6 col-lg-6 clgfrmimgltst5  padding-left ">
		  <div class="col-xs-12 col-sm-12  col-lg-12  clgletstbotom7  padding0">
            <div id="c-slot-4" data-box-id="489" class="mixed-apertures-69 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
			</div>
          </div>
        </div>
      </div>
		  
	         <div class="col-xs-12 col-sm-12  col-lg-12 ">
        <div class="row">
		    <div  class=" col-xs-12 col-sm-6 col-lg-6 clgfrmimgltst5  padding-left ">
		  <div class="col-xs-12 col-sm-12  col-lg-12  clgletstbotom7  padding0">
            <div id="c-slot-5" data-box-id="490" class="mixed-apertures-69 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
			</div>
          </div>

         <div  class="  col-xs-12 col-sm-4 col-lg-6 clgfrmimgltst5  padding-left ">
		  <div class="col-xs-12 col-sm-12  col-lg-6  clgletstbotom7  padding0">
            <div id="c-slot-6" data-box-id="491" class="apertures-upright-69 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
			</div>
			<div class="col-xs-12 col-sm-12  col-lg-6  clgletstbotom7  padding0"style="padding-left: 7px;">
            <div id="c-slot-7" data-box-id="492" class="apertures-upright-69 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
			</div>


		  <div class="col-xs-12 col-sm-12  col-lg-6   clgletstbotom7  padding0">
            <div id="c-slot-8" data-box-id="493" class="apertures-upright-69 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
			</div>
			<div class="col-xs-12 col-sm-12  col-lg-6  clgletstbotom7  padding0"style="padding-left: 7px;">
            <div id="c-slot-9" data-box-id="494" class="apertures-upright-69 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
			</div>
</div>
        </div>
      </div>
	  
	  
		  	  
		 <div class="col-xs-12 col-sm-12  col-lg-12 ">
        <div class="row">
	
		 <div  class=" col-xs-12 col-sm-3 col-lg-3 clgfrmimgltst5  padding-left ">
		  <div class="col-xs-12 col-sm-12  col-lg-12  clgletstbotom7  padding0">
            <div id="c-slot-10" data-box-id="495" class="apertures-upright-69 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
			</div>
		  <div class="col-xs-12 col-sm-12  col-lg-12  clgletstbotom7  padding0">
            <div id="c-slot-11" data-box-id="496" class="mixed-a-69 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
			</div>
          </div>
		  	
			
				    <div  class=" col-xs-12 col-sm-6 col-lg-6 clgfrmimgltst5  padding-left ">
		  <div class="col-xs-12 col-sm-12  col-lg-12  clgletstbotom7  padding0">
            <div id="c-slot-12" data-box-id="497" class="mixed-apertures-69 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
			</div>
			  <div class="col-xs-12 col-sm-12  col-lg-6  clgletstbotom7 clgfrmimgltst5  padding0">
            <div id="c-slot-13" data-box-id="498" class="apertures-upright-69 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
			</div>
			  <div class="col-xs-12 col-sm-12  col-lg-6  clgletstbotom7  padding0">
            <div id="c-slot-14" data-box-id="499" class="apertures-upright-69 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
			</div>
          </div>
			
			
			
			
			<div  class=" col-xs-12 col-sm-2 col-lg-3 clgfrmimgltst5  padding-left ">
		  <div class="col-xs-12 col-sm-12  col-lg-12  clgletstbotom7  padding0">
            <div id="c-slot-15" data-box-id="500" class="aperturerrss c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
			</div>
			<div class="col-xs-12 col-sm-12  col-lg-12  clgletstbotom7  padding0">
            <div id="c-slot-16" data-box-id="501" class="aperturerrss c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
			</div>
          </div>
        </div>
      </div>
      <div class="clearfix"></div>
	  <span id="page_2">
		<div placeholder="Dein Text hier" id="c-text" class="seconds">Enter text here (Optional)</div>
	  </span>
    </div>
    <div class="clearfix hidden-lg" style="height:20px;"></div>
  </div>
</div>         
</div>
<div id="get_slot_id"></div>
<!--Frame Div Ends-->
