<style>
    /*16-square css*/
    .square-same-70{
        background: rgb(238, 243, 250) none repeat scroll 0 0;
        cursor: pointer;
        height: 120px;
    }
    .paddingadjust{
        padding: 51px 50px 30px 55px !important;
    }
    .clgfrmimgltst5 {
        padding-right: 5px;
    }
    .clgletstbotom7 {
        margin-bottom: 5px;
    }

    /*square-4css end*/
</style>
<!--Frame Div Starts-->

<div class="col-xs-12 col-sm-8 col-md-8"> 
    <ul id="c-designer-header-tools">
        <li>Auto-fill<span class="icon-magic"></span></li>
        <li>Edit text<span class="icon-text-height"></span></li>
        <li>Clear collage<span class="icon-eraser"></span></li>
        <li class="pull-right"><a href="../index.php" style="color:#fff;">Change template<span class="icon-th"></span></a></li>
    </ul>
    <div id="c-designer">
        <div id="c-designer-layout-wrapper">
            <div id="c-layout" class="c-layout-43-3-h-txt-vacation1 col-xs-12 col-sm-12 col-lg-12 clgframboxvr2 paddingadjust" >



                <div class="col-xs-12 col-sm-12  col-lg-12 ">
                    <div class="row">
                        <div  class=" col-xs-12 col-sm-3 col-lg-3 clgfrmimgltst5 clgletstbotom7 padding-left ">
                            <div id="c-slot-1" data-box-id="502" class="square-same-70 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
                        </div>
                        <div  class=" col-xs-12 col-sm-3 col-lg-3 clgfrmimgltst5 clgletstbotom7 padding-left ">
                            <div id="c-slot-2" data-box-id="503" class="square-same-70 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
                        </div>
                        <div  class=" col-xs-12 col-sm-3 col-lg-3 clgfrmimgltst5 clgletstbotom7 padding-left ">
                            <div id="c-slot-3" data-box-id="504" class="square-same-70 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
                        </div>
                        <div  class=" col-xs-12 col-sm-3 col-lg-3 clgfrmimgltst5 clgletstbotom7 padding-left ">
                            <div id="c-slot-4" data-box-id="505" class="square-same-70 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
                        </div>
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12  col-lg-12 ">
                    <div class="row">
                        <div  class=" col-xs-12 col-sm-3 col-lg-3 clgfrmimgltst5 clgletstbotom7 padding-left ">
                            <div id="c-slot-5" data-box-id="506" class="square-same-70 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
                        </div>
                        <div  class=" col-xs-12 col-sm-3 col-lg-3 clgfrmimgltst5 clgletstbotom7 padding-left ">
                            <div id="c-slot-6" data-box-id="507" class="square-same-70 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
                        </div>
                        <div  class=" col-xs-12 col-sm-3 col-lg-3 clgfrmimgltst5 clgletstbotom7 padding-left ">
                            <div id="c-slot-7" data-box-id="508" class="square-same-70 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
                        </div>
                        <div  class=" col-xs-12 col-sm-3 col-lg-3 clgfrmimgltst5 clgletstbotom7 padding-left ">
                            <div id="c-slot-8" data-box-id="509" class="square-same-70 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
                        </div>
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12  col-lg-12 ">
                    <div class="row">
                        <div  class=" col-xs-12 col-sm-3 col-lg-3 clgfrmimgltst5 clgletstbotom7 padding-left ">
                            <div id="c-slot-9" data-box-id="510" class="square-same-70 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
                        </div>
                        <div  class=" col-xs-12 col-sm-3 col-lg-3 clgfrmimgltst5 clgletstbotom7 padding-left ">
                            <div id="c-slot-10" data-box-id="511" class="square-same-70 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
                        </div>
                        <div  class=" col-xs-12 col-sm-3 col-lg-3 clgfrmimgltst5 clgletstbotom7 padding-left ">
                            <div id="c-slot-11" data-box-id="512" class="square-same-70 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
                        </div>
                        <div  class=" col-xs-12 col-sm-3 col-lg-3 clgfrmimgltst5 clgletstbotom7 padding-left ">
                            <div id="c-slot-12" data-box-id="513" class="square-same-70 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
                        </div>
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12  col-lg-12 ">
                    <div class="row">
                        <div  class=" col-xs-12 col-sm-3 col-lg-3 clgfrmimgltst5 clgletstbotom7 padding-left ">
                            <div id="c-slot-13" data-box-id="514" class="square-same-70 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
                        </div>
                        <div  class=" col-xs-12 col-sm-3 col-lg-3 clgfrmimgltst5 clgletstbotom7 padding-left ">
                            <div id="c-slot-14" data-box-id="515" class="square-same-70 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
                        </div>
                        <div  class=" col-xs-12 col-sm-3 col-lg-3 clgfrmimgltst5 clgletstbotom7 padding-left ">
                            <div id="c-slot-15" data-box-id="516" class="square-same-70 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
                        </div>
                        <div  class=" col-xs-12 col-sm-3 col-lg-3 clgfrmimgltst5 clgletstbotom7 padding-left ">
                            <div id="c-slot-16" data-box-id="517" class="square-same-70 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
                        </div>
                    </div>
                </div>
                <div class="clearfix"></div>
                <span id="page_2">
                    <div placeholder="Dein Text hier" id="c-text" class="seconds">Enter text here (Optional)</div>
                </span>
            </div>
            <div class="clearfix hidden-lg" style="height:20px;"></div>
        </div>
    </div>         
</div>
<div id="get_slot_id"></div>
<!--Frame Div Ends-->