<style>
/*20-rectangle css*/
.rectangle-73{
    background: rgb(238, 243, 250) none repeat scroll 0 0;
    cursor: pointer;
    height: 62px;
}
.clgfrmimgltst5 {
    padding-right: 5px;
}
.clgletstbotom7 {
    margin-bottom: 5px;
}
.col-xs-15{
    width:20%;
}
#c-designer-layout-wrapper {
    float: left;
    height: 578px;
    padding: 30px;
    position: relative;
    width: 100%;
}
#c-designer {
    background: rgb(226, 226, 226) none repeat scroll 0 0;
    margin-bottom: 60px;
    min-height: 570px;
    padding: 1px;
    width: 100%;
}
/*20-rectangle end*/
</style>
<!--Frame Div Starts-->

<div class="col-xs-12 col-sm-8 col-md-8"> 
    <ul id="c-designer-header-tools">
        <li>Auto-fill<span class="icon-magic"></span></li>
        <li>Edit text<span class="icon-text-height"></span></li>
        <li>Clear collage<span class="icon-eraser"></span></li>
        <li class="pull-right"><a href="../index.php" style="color:#fff;">Change template<span class="icon-th"></span></a></li>
    </ul>
    <div id="c-designer">
        <div id="c-designer-layout-wrapper">
    <div id="c-layout" class="c-layout-43-3-h-txt-vacation1 col-xs-12 col-sm-12 col-lg-12 clgframboxvr2 paddingadjust" >
	
	
	
       <div class="col-xs-12 col-sm-12  col-lg-12 ">
        <div class="row">
           <div  class=" col-xs-12 col-sm-3 col-lg-2 col-xs-15  clgfrmimgltst5 clgletstbotom7 padding-left ">
            <div id="c-slot-1" data-box-id="536" class="rectangle-73 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
          </div>
           <div  class=" col-xs-12 col-sm-3 col-lg-2 col-xs-15  clgfrmimgltst5 clgletstbotom7 padding-left ">
            <div id="c-slot-2" data-box-id="537" class="rectangle-73 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
          </div>
           <div  class=" col-xs-12 col-sm-3 col-lg-2 col-xs-15  clgfrmimgltst5 clgletstbotom7 padding-left ">
            <div id="c-slot-3" data-box-id="538" class="rectangle-73 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
          </div>
           <div  class=" col-xs-12 col-sm-3 col-lg-2 col-xs-15  clgfrmimgltst5 clgletstbotom7 padding-left ">
            <div id="c-slot-4" data-box-id="539" class="rectangle-73 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
          </div>
           <div  class=" col-xs-12 col-sm-3 col-lg-2 col-xs-15  clgfrmimgltst5 clgletstbotom7 padding-left ">
            <div id="c-slot-5" data-box-id="540" class="rectangle-73 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
          </div>
        </div>
      </div>
       <div class="col-xs-12 col-sm-12  col-lg-12 ">
        <div class="row">
           <div  class=" col-xs-12 col-sm-3 col-lg-2 col-xs-15  clgfrmimgltst5 clgletstbotom7 padding-left ">
            <div id="c-slot-6" data-box-id="541" class="rectangle-73 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
          </div>
           <div  class=" col-xs-12 col-sm-3 col-lg-2 col-xs-15  clgfrmimgltst5 clgletstbotom7 padding-left ">
            <div id="c-slot-7" data-box-id="542" class="rectangle-73 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
          </div>
           <div  class=" col-xs-12 col-sm-3 col-lg-2 col-xs-15  clgfrmimgltst5 clgletstbotom7 padding-left ">
            <div id="c-slot-8" data-box-id="543" class="rectangle-73 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
          </div>
           <div  class=" col-xs-12 col-sm-3 col-lg-2 col-xs-15  clgfrmimgltst5 clgletstbotom7 padding-left ">
            <div id="c-slot-9" data-box-id="544" class="rectangle-73 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
          </div>
           <div  class=" col-xs-12 col-sm-3 col-lg-2 col-xs-15  clgfrmimgltst5 clgletstbotom7 padding-left ">
            <div id="c-slot-10" data-box-id="545" class="rectangle-73 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
          </div>
        </div>
      </div>
       <div class="col-xs-12 col-sm-12  col-lg-12 ">
        <div class="row">
           <div  class=" col-xs-12 col-sm-3 col-lg-2 col-xs-15  clgfrmimgltst5 clgletstbotom7 padding-left ">
            <div id="c-slot-11" data-box-id="546" class="rectangle-73 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
          </div>
           <div  class=" col-xs-12 col-sm-3 col-lg-2 col-xs-15  clgfrmimgltst5 clgletstbotom7 padding-left ">
            <div id="c-slot-12" data-box-id="547" class="rectangle-73 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
          </div>
           <div  class=" col-xs-12 col-sm-3 col-lg-2 col-xs-15  clgfrmimgltst5 clgletstbotom7 padding-left ">
            <div id="c-slot-13" data-box-id="548" class="rectangle-73 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
          </div>
           <div  class=" col-xs-12 col-sm-3 col-lg-2 col-xs-15  clgfrmimgltst5 clgletstbotom7 padding-left ">
            <div id="c-slot-14" data-box-id="549" class="rectangle-73 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
          </div>
           <div  class=" col-xs-12 col-sm-3 col-lg-2 col-xs-15  clgfrmimgltst5 clgletstbotom7 padding-left ">
            <div id="c-slot-15" data-box-id="550" class="rectangle-73 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
          </div>
        </div>
      </div>
       <div class="col-xs-12 col-sm-12  col-lg-12 ">
        <div class="row">
           <div  class=" col-xs-12 col-sm-3 col-lg-2 col-xs-15  clgfrmimgltst5 clgletstbotom7 padding-left ">
            <div id="c-slot-16" data-box-id="551" class="rectangle-73 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
          </div>
           <div  class=" col-xs-12 col-sm-3 col-lg-2 col-xs-15  clgfrmimgltst5 clgletstbotom7 padding-left ">
            <div id="c-slot-17" data-box-id="552" class="rectangle-73 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
          </div>
           <div  class=" col-xs-12 col-sm-3 col-lg-2 col-xs-15  clgfrmimgltst5 clgletstbotom7 padding-left ">
            <div id="c-slot-18" data-box-id="553" class="rectangle-73 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
          </div>
           <div  class=" col-xs-12 col-sm-3 col-lg-2 col-xs-15  clgfrmimgltst5 clgletstbotom7 padding-left ">
            <div id="c-slot-19" data-box-id="554" class="rectangle-73 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
          </div>
           <div  class=" col-xs-12 col-sm-3 col-lg-2 col-xs-15  clgfrmimgltst5 clgletstbotom7 padding-left ">
            <div id="c-slot-20" data-box-id="555" class="rectangle-73 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
          </div>
        </div>
      </div>
      <div class="clearfix"></div>
	  <span id="page_2">
		<div placeholder="Dein Text hier" id="c-text" class="seconds">Enter text here (Optional)</div>
	  </span>
    </div>
    <div class="clearfix hidden-lg" style="height:20px;"></div>
  </div>
</div>         
</div>
<div id="get_slot_id"></div>
<!--Frame Div Ends-->