<style>
    /*18-apertures css*/
    .apertures-78{
        background:#eef3fa;
        cursor:pointer;
        height: 76px;	
    }
    .mixed-apertures-78{
        background:#eef3fa;
        cursor:pointer;
        height: 158px;	
    }
    .mixed-a-78{
        background:#eef3fa;
        cursor:pointer;
        height: 99px;	
    }
    .mixed-vb-78{
        background:#eef3fa;
        cursor:pointer;
        height: 53px;	
    }
    .padding0{
        padding:0px;
    }
    .clgfrmimgltst5 {
        padding-right: 6px;
    }
    .clgletstbotom7 {
        margin-bottom: 6px;
    }
    .paddingadjust{
        padding: 51px 0 30px 55px !important;
    }
    #c-designer-layout-wrapper {
        float: left;
        height: 578px;
        padding: 30px;
        position: relative;
        width: 100%;
    }
    #c-designer {
        background: rgb(226, 226, 226) none repeat scroll 0 0;
        margin-bottom: 60px;
        min-height: 620px;
        padding: 1px;
        width: 100%;
    }
    /*square-4css end*/
</style>
<!--Frame Div Starts-->
<div class="col-xs-12 col-sm-8 col-md-8"> 
    <ul id="c-designer-header-tools">
        <li>Auto-fill<span class="icon-magic"></span></li>
        <li>Edit text<span class="icon-text-height"></span></li>
        <li>Clear collage<span class="icon-eraser"></span></li>
        <li class="pull-right"><a href="../index.php" style="color:#fff;">Change template<span class="icon-th"></span></a></li>
    </ul>
    <div id="c-designer">
        <div id="c-designer-layout-wrapper">
            <div id="c-layout" class="c-layout-43-3-h-txt-vacation1 col-xs-12 col-sm-12 col-lg-12 clgframboxvr2 paddingadjust" >
                <div class="col-xs-12 col-sm-12  col-lg-12 ">
                    <div class="row">
                        <div  class=" col-xs-12 col-sm-2 col-lg-2 clgfrmimgltst5  padding-left ">
                            <div class="col-xs-12 col-sm-12  col-lg-12  clgletstbotom7  padding0">
                                <div id="c-slot-1" data-box-id="596" class="mixed-a-78 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
                            </div>
                            <div class="col-xs-12 col-sm-12  col-lg-12  clgletstbotom7  padding0">
                                <div id="c-slot-2" data-box-id="597" class="mixed-vb-78 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
                            </div>
                            <div class="col-xs-12 col-sm-12  col-lg-12  clgletstbotom7  padding0">
                                <div id="c-slot-3" data-box-id="598" class="mixed-vb-78 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
                            </div>
                            <div class="col-xs-12 col-sm-12  col-lg-12  clgletstbotom7  padding0">
                                <div id="c-slot-4" data-box-id="599" class="mixed-a-78 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
                            </div>
                        </div>
                        <div  class=" col-xs-12 col-sm-2 col-lg-2 clgfrmimgltst5  padding-left ">
                            <div class="col-xs-12 col-sm-12  col-lg-12  clgletstbotom7  padding0">
                                <div id="c-slot-5" data-box-id="600" class="apertures-78 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
                            </div>
                            <div class="col-xs-12 col-sm-12  col-lg-12  clgletstbotom7  padding0">
                                <div id="c-slot-6" data-box-id="601" class="apertures-78 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
                            </div>
                            <div class="col-xs-12 col-sm-12  col-lg-12  clgletstbotom7  padding0">
                                <div id="c-slot-7" data-box-id="602" class="apertures-78 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
                            </div>
                            <div class="col-xs-12 col-sm-12  col-lg-12  clgletstbotom7  padding0">
                                <div id="c-slot-8" data-box-id="603" class="apertures-78 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
                            </div>
                        </div>
                        <div  class=" col-xs-12 col-sm-3 col-lg-3 clgfrmimgltst5  padding-left ">
                            <div class="col-xs-12 col-sm-12  col-lg-12  clgletstbotom7  padding0">
                                <div id="c-slot-9" data-box-id="604" class="mixed-apertures-78 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
                            </div>
                            <div class="col-xs-12 col-sm-12  col-lg-12  clgletstbotom7  padding0">
                                <div id="c-slot-10" data-box-id="605" class="mixed-apertures-78 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
                            </div>
                        </div>
                        <div  class=" col-xs-12 col-sm-2 col-lg-2 clgfrmimgltst5  padding-left ">
                            <div class="col-xs-12 col-sm-12  col-lg-12  clgletstbotom7  padding0">
                                <div id="c-slot-11" data-box-id="606" class="apertures-78 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
                            </div>
                            <div class="col-xs-12 col-sm-12  col-lg-12  clgletstbotom7  padding0">
                                <div id="c-slot-12" data-box-id="607" class="apertures-78 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
                            </div>
                            <div class="col-xs-12 col-sm-12  col-lg-12  clgletstbotom7  padding0">
                                <div id="c-slot-13" data-box-id="608" class="apertures-78 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
                            </div>
                            <div class="col-xs-12 col-sm-12  col-lg-12  clgletstbotom7  padding0">
                                <div id="c-slot-14" data-box-id="609" class="apertures-78 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
                            </div>
                        </div>
                        <div  class=" col-xs-12 col-sm-2 col-lg-2 clgfrmimgltst5  padding-left ">
                            <div class="col-xs-12 col-sm-12  col-lg-12  clgletstbotom7  padding0">
                                <div id="c-slot-15" data-box-id="610" class="mixed-a-78 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
                            </div>
                            <div class="col-xs-12 col-sm-12  col-lg-12  clgletstbotom7  padding0">
                                <div id="c-slot-16" data-box-id="611" class="mixed-vb-78 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
                            </div>
                            <div class="col-xs-12 col-sm-12  col-lg-12  clgletstbotom7  padding0">
                                <div id="c-slot-17" data-box-id="612" class="mixed-vb-78 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
                            </div>
                            <div class="col-xs-12 col-sm-12  col-lg-12  clgletstbotom7  padding0">
                                <div id="c-slot-18" data-box-id="613" class="mixed-a-78 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="clearfix"></div>
                <span id="page_2">
                    <div placeholder="Dein Text hier" id="c-text" class="seconds">Enter text here (Optional)</div>
                </span>
            </div>
            <div class="clearfix hidden-lg" style="height:20px;"></div>
        </div>
    </div>         
</div>
<div id="get_slot_id"></div>
<!--Frame Div Ends-->