<style>
/*25-square css*/
.square-77{
    background: rgb(238, 243, 250) none repeat scroll 0 0;
    cursor: pointer;
    height: 95px;
}
.clgfrmimgltst5 {
    padding-right: 10px;
}
.clgletstbotom7 {
    margin-bottom: 10px;
}
.col-xs-15{
    width:20%;
}
#c-designer-layout-wrapper {
    float: left;
    height: 578px;
    padding: 34px;
    position: relative;
    width: 100%;
}
#c-designer {
    background: rgb(226, 226, 226) none repeat scroll 0 0;
    margin-bottom: 60px;
    min-height: 690px;
    padding: 1px;
    width: 100%;
}
/*20-square end*/
</style>
<!--Frame Div Starts-->
<div class="col-xs-12 col-sm-8 col-md-8"> 
    <ul id="c-designer-header-tools">
        <li>Auto-fill<span class="icon-magic"></span></li>
        <li>Edit text<span class="icon-text-height"></span></li>
        <li>Clear collage<span class="icon-eraser"></span></li>
        <li class="pull-right"><a href="../index.php" style="color:#fff;">Change template<span class="icon-th"></span></a></li>
    </ul>
    <div id="c-designer">
        <div id="c-designer-layout-wrapper">
    <div id="c-layout" class="c-layout-43-3-h-txt-vacation1 col-xs-12 col-sm-12 col-lg-12 clgframboxvr2 paddingadjust" >
       <div class="col-xs-12 col-sm-12  col-lg-12 ">
        <div class="row">
           <div  class=" col-xs-12 col-sm-3 col-lg-2 col-xs-15  clgfrmimgltst5 clgletstbotom7 padding-left ">
            <div id="c-slot-1" data-box-id="614" class="square-77 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
          </div>
           <div  class=" col-xs-12 col-sm-3 col-lg-2 col-xs-15  clgfrmimgltst5 clgletstbotom7 padding-left ">
            <div id="c-slot-2" data-box-id="615" class="square-77 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
          </div>
           <div  class=" col-xs-12 col-sm-3 col-lg-2 col-xs-15  clgfrmimgltst5 clgletstbotom7 padding-left ">
            <div id="c-slot-3" data-box-id="616" class="square-77 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
          </div>
           <div  class=" col-xs-12 col-sm-3 col-lg-2 col-xs-15  clgfrmimgltst5 clgletstbotom7 padding-left ">
            <div id="c-slot-4" data-box-id="617" class="square-77 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
          </div>
           <div  class=" col-xs-12 col-sm-3 col-lg-2 col-xs-15  clgfrmimgltst5 clgletstbotom7 padding-left ">
            <div id="c-slot-5" data-box-id="618" class="square-77 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
          </div>
        </div>
      </div>
       <div class="col-xs-12 col-sm-12  col-lg-12 ">
        <div class="row">
           <div  class=" col-xs-12 col-sm-3 col-lg-2 col-xs-15  clgfrmimgltst5 clgletstbotom7 padding-left ">
            <div id="c-slot-6" data-box-id="619" class="square-77 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
          </div>
           <div  class=" col-xs-12 col-sm-3 col-lg-2 col-xs-15  clgfrmimgltst5 clgletstbotom7 padding-left ">
            <div id="c-slot-7" data-box-id="620" class="square-77 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
          </div>
           <div  class=" col-xs-12 col-sm-3 col-lg-2 col-xs-15  clgfrmimgltst5 clgletstbotom7 padding-left ">
            <div id="c-slot-8" data-box-id="621" class="square-77 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
          </div>
           <div  class=" col-xs-12 col-sm-3 col-lg-2 col-xs-15  clgfrmimgltst5 clgletstbotom7 padding-left ">
            <div id="c-slot-9" data-box-id="622" class="square-77 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
          </div>
           <div  class=" col-xs-12 col-sm-3 col-lg-2 col-xs-15  clgfrmimgltst5 clgletstbotom7 padding-left ">
            <div id="c-slot-10" data-box-id="623" class="square-77 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
          </div>
        </div>
      </div>
       <div class="col-xs-12 col-sm-12  col-lg-12 ">
        <div class="row">
           <div  class=" col-xs-12 col-sm-3 col-lg-2 col-xs-15  clgfrmimgltst5 clgletstbotom7 padding-left ">
            <div id="c-slot-11" data-box-id="624" class="square-77 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
          </div>
           <div  class=" col-xs-12 col-sm-3 col-lg-2 col-xs-15  clgfrmimgltst5 clgletstbotom7 padding-left ">
            <div id="c-slot-12" data-box-id="625" class="square-77 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
          </div>
           <div  class=" col-xs-12 col-sm-3 col-lg-2 col-xs-15  clgfrmimgltst5 clgletstbotom7 padding-left ">
            <div id="c-slot-13" data-box-id="626" class="square-77 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
          </div>
           <div  class=" col-xs-12 col-sm-3 col-lg-2 col-xs-15  clgfrmimgltst5 clgletstbotom7 padding-left ">
            <div id="c-slot-14" data-box-id="627" class="square-77 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
          </div>
           <div  class=" col-xs-12 col-sm-3 col-lg-2 col-xs-15  clgfrmimgltst5 clgletstbotom7 padding-left ">
            <div id="c-slot-15" data-box-id="628" class="square-77 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
          </div>
        </div>
       </div>
       <div class="col-xs-12 col-sm-12  col-lg-12 ">
        <div class="row">
           <div  class=" col-xs-12 col-sm-3 col-lg-2 col-xs-15  clgfrmimgltst5 clgletstbotom7 padding-left ">
            <div id="c-slot-16" data-box-id="629" class="square-77 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
          </div>
           <div  class=" col-xs-12 col-sm-3 col-lg-2 col-xs-15  clgfrmimgltst5 clgletstbotom7 padding-left ">
            <div id="c-slot-17" data-box-id="630" class="square-77 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
          </div>
           <div  class=" col-xs-12 col-sm-3 col-lg-2 col-xs-15  clgfrmimgltst5 clgletstbotom7 padding-left ">
            <div id="c-slot-18" data-box-id="631" class="square-77 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
          </div>
           <div  class=" col-xs-12 col-sm-3 col-lg-2 col-xs-15  clgfrmimgltst5 clgletstbotom7 padding-left ">
            <div id="c-slot-19" data-box-id="632" class="square-77 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
          </div>
           <div  class=" col-xs-12 col-sm-3 col-lg-2 col-xs-15  clgfrmimgltst5 clgletstbotom7 padding-left ">
            <div id="c-slot-20" data-box-id="633" class="square-77 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
          </div>
        </div>
      </div>
       <div class="col-xs-12 col-sm-12  col-lg-12 ">
        <div class="row">
           <div  class=" col-xs-12 col-sm-3 col-lg-2 col-xs-15  clgfrmimgltst5 clgletstbotom7 padding-left ">
            <div id="c-slot-21" data-box-id="634" class="square-77 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
          </div>
           <div  class=" col-xs-12 col-sm-3 col-lg-2 col-xs-15  clgfrmimgltst5 clgletstbotom7 padding-left ">
            <div id="c-slot-22" data-box-id="635" class="square-77 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
          </div>
           <div  class=" col-xs-12 col-sm-3 col-lg-2 col-xs-15  clgfrmimgltst5 clgletstbotom7 padding-left ">
            <div id="c-slot-23" data-box-id="636" class="square-77 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
          </div>
           <div  class=" col-xs-12 col-sm-3 col-lg-2 col-xs-15  clgfrmimgltst5 clgletstbotom7 padding-left ">
            <div id="c-slot-24" data-box-id="637" class="square-77 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
          </div>
           <div  class=" col-xs-12 col-sm-3 col-lg-2 col-xs-15  clgfrmimgltst5 clgletstbotom7 padding-left ">
            <div id="c-slot-25" data-box-id="638" class="square-77 c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
          </div>
        </div>
      </div>
      <div class="clearfix"></div>
	  <span id="page_2">
		<div placeholder="Dein Text hier" id="c-text" class="seconds">Enter text here (Optional)</div>
	  </span>
    </div>
    <div class="clearfix hidden-lg" style="height:20px;"></div>
  </div>
</div>         
</div>
<div id="get_slot_id"></div>
<!--Frame Div Ends-->