<style>
.mixed-3lg{
	background:#eef3fa;
	cursor:pointer;
	height:400px;
	overflow:hidden;
}
.mixed-3sm{
	background:#eef3fa;
	cursor:pointer;
	height:190px;	
	overflow:hidden;
	margin-bottom:20px;
}
.paddingadjust{
	padding:53px 40px 20px 50px !important
}
#page_2 {
    bottom: -8px;
    color: #000000;
    font-family: "Open Sans","sans-serif";
    font-size: 22px;
    min-height: 22px;
    position: relative;
    text-align: center;
    top: 3px;
    width: 530px;
}
</style>
<!--Frame Div Starts-->
<div class="col-xs-12 col-sm-8 col-md-8"> 
    <ul id="c-designer-header-tools">
        <li>Auto-fill<span class="icon-magic"></span></li>
        <li>Edit text<span class="icon-text-height"></span></li>
        <li>Clear collage<span class="icon-eraser"></span></li>
        <li class="pull-right"><a href="../index.php" style="color:#fff;">Change template<span class="icon-th"></span></a></li>
    </ul>
    <div id="c-designer">
        <div id="c-designer-layout-wrapper">
    <div id="c-layout" class="c-layout-43-3-h-txt-vacation1 col-xs-12 col-sm-12 col-lg-12 clgframboxvr2 paddingadjust" >
      <div class="col-xs-12 col-sm-6  col-lg-6 ">
        <div class="row">
          <div  class=" col-xs-12 col-sm-12 col-lg-12 clgfrmimgltst5 clgletstbotom7  padding-left">
            <div id="c-slot-1" data-box-id="29" class="mixed-3lg c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;" ></div>
          </div>
          
        </div>
      </div>
      <div class="col-xs-12 col-sm-6  col-lg-6 ">
        <div class="row">
          <div class="col-xs-12 col-sm-12 col-lg-12 clgfrmimgltst5    padding-left">
              <a href="../../../../../C:/Users/PHP Asif/AppData/Local/Temp/d8noky7v.bmp"></a>
            <div id="c-slot-2" data-box-id="30" class="mixed-3sm c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
          </div>
          <div class="col-xs-12 col-sm-12 col-lg-12 clgfrmimgltst5    padding-left">
            <div id="c-slot-3" data-box-id="31" class="mixed-3sm c-layout-slot rect-v pos-2 ui-droppable frm2ht" style="overflow:hidden;"></div>
          </div>
                </div>
      </div>
      <div class="clearfix"></div>
       <span id="page_2">
                <div placeholder="Dein Text hier" id="c-text" class="seconds">Enter text here (Optional)</div>
            </span>
    </div>
    <div class="clearfix hidden-lg" style="height:20px;"></div>
  </div>
</div>         
</div>
<div id="get_slot_id"></div>
<!--Frame Div Ends-->