<?php include 'header.php'; ?>
<!--Frame Div Starts-->
<div class="col-xs-12 col-sm-8 col-md-8"> 
    <ul id="c-designer-header-tools">
        <li>Auto-fill<span class="icon-magic"></span></li>
        <li>Edit text<span class="icon-text-height"></span></li>
        <li>Clear collage<span class="icon-eraser"></span></li>
        <li class="pull-right"><a href="../index.php" style="color:#fff;">Change template<span class="icon-th"></span></a></li>
    </ul>
    <div id="c-designer">
        <div id="c-designer-layout-wrapper">
            <div id="c-layout" class="c-layout-43-3-h-txt-vacation1 col-xs-12 col-sm-12  col-lg-12 If_tears_could clgfrminrletst3">
                <div class=" col-xs-12 col-sm-4 col-lg-3 wedding_anni_87">
                    <label>&nbsp;</label>
                    <p>&nbsp;</p>
                    <div  id="c-slot-1" data-box-id="719" class="c-layout-slot rect-v pos-1 ui-droppable rightpading Dream_Big_87" style="overflow:hidden;"></div>
                </div>          
                <div id="c-text"></div>
                <div class="clearfix"></div>
            </div>
        </div>
    </div>         
</div>
<div id="get_slot_id"></div>
<!--Frame Div Ends-->
<?php
include 'uploadimage_sidebar_one.php';
include 'footer.php';
?>