<?php include 'header.php'; ?>
<!--Frame Div Starts-->
<div class="col-xs-12 col-sm-8 col-md-8"> 
    <ul id="c-designer-header-tools">
        <li>Auto-fill<span class="icon-magic"></span></li>
        <li>Edit text<span class="icon-text-height"></span></li>
        <li>Clear collage<span class="icon-eraser"></span></li>
        <li class="pull-right"><a href="../index.php" style="color:#fff;">Change template<span class="icon-th"></span></a></li>
    </ul>
    <div id="c-designer">
        <div id="c-designer-layout-wrapper">
            <div id="c-layout" class="c-layout-43-3-h-txt-vacation1 col-xs-12 col-sm-12  col-lg-12  Baby_Girl  clgfrminrletst3">
                <div class=" col-xs-12 col-sm-4 col-lg-3 clgbabybox  clgbabybox">
                    <label>&nbsp;</label>
                    <p>&nbsp;</p>
                    <div  id="c-slot-1" data-box-id="721" class="c-layout-slot rect-v pos-1 ui-droppable rightpading clgbabibox1" style="overflow:hidden;"></div>
                </div>
                <div class="col-xs-12 col-sm-4  col-lg-5 padding clgbabybox2">
                    <div id="c-slot-2" data-box-id="722" class="c-layout-slot rect-v pos-2 ui-droppable clgbabibox2" style="overflow:hidden;"></div>
                </div>
                <div class="col-xs-12 col-sm-4  col-lg-4 leftpading clgbabybox  clgbabybox" >
                    <div id="c-slot-3" data-box-id="723" class="c-layout-slot rect-v pos-3 ui-droppable clgbabibox1" style="padding:0px;padding-left: 2.5%; overflow:hidden;"></div>
                    <label>&nbsp;</label>
                    <p>&nbsp;</p>
                </div>
               <div id="c-text"></div>

                <div class="clearfix"></div>
            </div>
        </div>
    </div>         
</div>

<div id="get_slot_id"></div>
<!--Frame Div Ends-->
<?php
include 'uploadimage_sidebar.php';
include 'footer.php';
?>